#!/usr/bin/env python3
import argparse
import json
import math
import re
from pathlib import Path

def _constraints_to_fix(ndf, constraints):
    if constraints is None:
        return None
    if isinstance(constraints, list):
        if all(isinstance(v, bool) for v in constraints):
            if len(constraints) != ndf:
                raise ValueError(f"constraints bool list length {len(constraints)} != ndf {ndf}")
            return [1 if v else 0 for v in constraints]
        # assume list of 1-based dof indices
        fix = [0] * ndf
        for dof in constraints:
            if not isinstance(dof, int):
                raise ValueError("constraints must be list of ints or bools")
            if dof < 1 or dof > ndf:
                raise ValueError(f"constraint dof {dof} out of range 1..{ndf}")
            fix[dof - 1] = 1
        return fix
    raise ValueError("constraints must be list")


def _write_header(f):
    f.write("# Auto-generated by json_to_tcl.py\n")


def _require_field(obj, key):
    if key not in obj:
        raise ValueError(f"missing required field: {key}")
    return obj[key]


def _choose_vecxz(n1, n2):
    dx = n2["x"] - n1["x"]
    dy = n2["y"] - n1["y"]
    dz = n2["z"] - n1["z"]
    length = math.sqrt(dx * dx + dy * dy + dz * dz)
    if length == 0.0:
        raise ValueError("zero-length element")
    ax = dx / length
    ay = dy / length
    az = dz / length

    candidates = ((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0))
    for vx, vy, vz in candidates:
        dot = abs(ax * vx + ay * vy + az * vz)
        if dot < 0.9:
            return (vx, vy, vz)
    return (1.0, 0.0, 0.0)


def _normalize_time_series(ts):
    if ts is None:
        return []
    if isinstance(ts, dict):
        return [ts]
    if isinstance(ts, list):
        return ts
    raise ValueError("time_series must be a list or object")


def _format_list(values):
    return " ".join(str(v) for v in values)


def _resolve_optional_repo_path(path_text, repo_root: Path):
    if not isinstance(path_text, str) or not path_text:
        return None
    path_obj = Path(path_text)
    if path_obj.is_absolute():
        return path_obj
    return (repo_root / path_obj).resolve()


def _load_path_time_series_values(ts, case_dir: Path, case_data: dict):
    values_path = ts.get("values_path", ts.get("path"))
    if values_path is None:
        raise ValueError("Path time_series missing values_path")

    src = Path(values_path)
    candidates = []
    if src.is_absolute():
        candidates.append(src)
    else:
        repo_root = Path(__file__).resolve().parents[1]
        candidates.append((case_dir / src).resolve())
        candidates.append((repo_root / src).resolve())

        source_example = _resolve_optional_repo_path(case_data.get("source_example"), repo_root)
        if source_example is not None:
            candidates.append((source_example.parent / src).resolve())

        source_doc = _resolve_optional_repo_path(case_data.get("source_doc"), repo_root)
        if source_doc is not None:
            candidates.append((source_doc.parent / src).resolve())

        migration = case_data.get("migration", {})
        ground_motion = migration.get("ground_motion", {}) if isinstance(migration, dict) else {}
        source_file = _resolve_optional_repo_path(ground_motion.get("source_file"), repo_root)
        if source_file is not None:
            candidates.append((source_file.parent / src).resolve())

        # Keep backward compatibility with callers that rely on current working directory.
        candidates.append(Path(values_path))

    src = next((p for p in candidates if p.exists()), None)
    if src is None:
        checked = ", ".join(str(p) for p in candidates)
        raise ValueError(
            f"Path time_series values_path not found: {values_path}; checked: {checked}"
        )
    text = src.read_text(encoding="utf-8")
    tokens = re.findall(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eEdD][-+]?\d+)?", text)
    if not tokens:
        raise ValueError(f"Path time_series values_path had no numeric values: {src}")
    return [float(tok.replace("D", "E").replace("d", "e")) for tok in tokens]


def _emit_time_series(f, ts, case_dir: Path, case_data: dict):
    ts_type = ts.get("type")
    tag = ts.get("tag")
    if ts_type is None or tag is None:
        raise ValueError("time_series requires type and tag")
    factor = ts.get("factor", 1.0)

    if ts_type == "Constant":
        f.write(f"timeSeries Constant {tag} -factor {factor}\n")
    elif ts_type == "Linear":
        f.write(f"timeSeries Linear {tag} -factor {factor}\n")
    elif ts_type in ("Path", "PathFile"):
        if "dt" in ts and "time" in ts:
            raise ValueError("Path time_series cannot specify both dt and time")
        if "values" in ts and ("values_path" in ts or "path" in ts):
            raise ValueError("Path time_series cannot specify both values and values_path/path")
        values = ts.get("values")
        if values is None:
            values = _load_path_time_series_values(ts, case_dir, case_data)
        line = f"timeSeries Path {tag} "
        if "dt" in ts:
            line += f"-dt {ts['dt']} "
        elif "time" in ts:
            line += f"-time {{{_format_list(ts['time'])}}} "
        else:
            raise ValueError("Path time_series requires dt or time")
        line += f"-values {{{_format_list(values)}}} -factor {factor}"
        if ts.get("use_last", False):
            line += " -useLast"
        f.write(line + "\n")
    elif ts_type == "Trig":
        for key in ("t_start", "t_finish", "period"):
            if key not in ts:
                raise ValueError(f"Trig time_series missing {key}")
        line = (
            f"timeSeries Trig {tag} {ts['t_start']} {ts['t_finish']} {ts['period']}"
            f" -phaseShift {ts.get('phase_shift', 0.0)}"
            f" -factor {factor}"
            f" -zeroShift {ts.get('zero_shift', 0.0)}"
        )
        f.write(line + "\n")
    else:
        raise ValueError(f"unsupported time_series type: {ts_type}")


def _algorithm_cmd(algorithm_name, cfg, prefix=""):
    if algorithm_name == "ModifiedNewtonInitial":
        return "ModifiedNewton -initial"
    if algorithm_name == "Broyden":
        count = int(cfg.get(f"{prefix}broyden_count", 8))
        return f"Broyden {count}"
    if algorithm_name == "NewtonLineSearch":
        eta = float(cfg.get(f"{prefix}line_search_eta", 0.8))
        return f"NewtonLineSearch {eta}"
    return algorithm_name


def _emit_recorders(f, recorders, node_by_id, ndf):
    for rec in recorders:
        rec_type = rec["type"]
        if rec_type == "node_displacement":
            dofs = rec["dofs"]
            output = rec.get("output", "node_disp")
            for node_id in rec["nodes"]:
                filename = f"{output}_node{node_id}.out"
                f.write(
                    f"recorder Node -file {filename} -node {node_id} -dof {' '.join(str(d) for d in dofs)} disp\n"
                )
        elif rec_type == "element_force":
            output = rec.get("output", "element_force")
            for elem_id in rec["elements"]:
                filename = f"{output}_ele{elem_id}.out"
                f.write(f"recorder Element -file {filename} -ele {elem_id} force\n")
        elif rec_type == "node_reaction":
            dofs = rec["dofs"]
            output = rec.get("output", "reaction")
            for node_id in rec["nodes"]:
                filename = f"{output}_node{node_id}.out"
                f.write(
                    f"recorder Node -file {filename} -node {node_id} -dof {' '.join(str(d) for d in dofs)} reaction\n"
                )
        elif rec_type == "drift":
            i_node = rec["i_node"]
            j_node = rec["j_node"]
            dof = rec["dof"]
            perp_dirn = rec["perp_dirn"]
            output = rec.get("output", "drift")
            filename = f"{output}_i{i_node}_j{j_node}.out"
            f.write(
                f"recorder Drift -file {filename} -iNode {i_node} -jNode {j_node} -dof {dof} -perpDirn {perp_dirn}\n"
            )
        elif rec_type == "envelope_element_force":
            output = rec.get("output", "envelope_element_force")
            for elem_id in rec["elements"]:
                filename = f"{output}_ele{elem_id}.out"
                f.write(
                    f"recorder EnvelopeElement -file {filename} -ele {elem_id} forces\n"
                )
        elif rec_type == "section_force" or rec_type == "section_deformation":
            output = rec.get("output", rec_type)
            response = "force" if rec_type == "section_force" else "deformation"
            sections = rec.get("sections")
            if sections is None:
                if "section" not in rec:
                    raise ValueError(f"{rec_type} recorder requires section or sections")
                sections = [rec["section"]]
            if not isinstance(sections, list) or len(sections) == 0:
                raise ValueError(f"{rec_type} recorder requires non-empty sections")
            for elem_id in rec["elements"]:
                for sec_no in sections:
                    sec_idx = int(sec_no)
                    filename = f"{output}_ele{elem_id}_sec{sec_idx}.out"
                    f.write(
                        f"recorder Element -file {filename} -ele {elem_id} section {sec_idx} {response}\n"
                    )
        elif rec_type == "modal_eigen":
            # Modal outputs are emitted explicitly after `eigen`, not through recorder commands.
            pass
        else:
            raise ValueError(f"unsupported recorder type: {rec_type}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("json_file")
    parser.add_argument("tcl_out")
    args = parser.parse_args()

    json_path = Path(args.json_file)
    data = json.loads(json_path.read_text())
    case_dir = json_path.parent
    schema_version = data.get("schema_version", "1.0")
    if schema_version != "1.0":
        raise ValueError(f"unsupported schema_version: {schema_version}")

    model = _require_field(data, "model")
    ndm = _require_field(model, "ndm")
    ndf = _require_field(model, "ndf")

    nodes = _require_field(data, "nodes")
    elements = _require_field(data, "elements")
    sections = {sec["id"]: sec for sec in data.get("sections", [])}
    materials = {mat["id"]: mat for mat in data.get("materials", [])}
    node_by_id = {node["id"]: node for node in nodes}

    recorders = data.get("recorders", [])

    tcl_path = Path(args.tcl_out)
    tcl_path.parent.mkdir(parents=True, exist_ok=True)

    with tcl_path.open("w", encoding="utf-8") as f:
        _write_header(f)
        f.write(f"model BasicBuilder -ndm {ndm} -ndf {ndf}\n")

        for node in nodes:
            node_id = node["id"]
            if ndm == 2:
                f.write(f"node {node_id} {node['x']} {node['y']}\n")
            elif ndm == 3:
                if "z" not in node:
                    raise ValueError(f"ndm=3 node {node_id} missing z coordinate")
                f.write(f"node {node_id} {node['x']} {node['y']} {node['z']}\n")
            else:
                raise ValueError("ndm must be 2 or 3")

            fix = _constraints_to_fix(ndf, node.get("constraints"))
            if fix is not None:
                f.write(f"fix {node_id} {' '.join(str(v) for v in fix)}\n")

        mp_constraints = data.get("mp_constraints", [])
        for mpc in mp_constraints:
            mpc_type = mpc.get("type")
            if mpc_type != "equalDOF":
                raise ValueError(f"unsupported mp constraint type: {mpc_type}")
            retained = mpc.get("retained_node")
            constrained_node = mpc.get("constrained_node")
            dofs = mpc.get("dofs", [])
            if retained not in node_by_id:
                raise ValueError(f"equalDOF retained_node {retained} not found")
            if constrained_node not in node_by_id:
                raise ValueError(f"equalDOF constrained_node {constrained_node} not found")
            if not isinstance(dofs, list) or not dofs:
                raise ValueError("equalDOF requires non-empty dofs list")
            dof_vals = []
            for dof in dofs:
                if not isinstance(dof, int) or dof < 1 or dof > ndf:
                    raise ValueError(f"equalDOF dof {dof} out of range 1..{ndf}")
                dof_vals.append(str(dof))
            f.write(f"equalDOF {retained} {constrained_node} {' '.join(dof_vals)}\n")

        # Nodal masses (lumped)
        masses = data.get("masses", [])
        if masses:
            mass_map = {}
            for entry in masses:
                node_id = entry["node"]
                dof = entry["dof"]
                value = entry["value"]
                if dof < 1 or dof > ndf:
                    raise ValueError(f"mass dof {dof} out of range 1..{ndf}")
                vec = mass_map.setdefault(node_id, [0.0] * ndf)
                vec[dof - 1] += value
            for node_id, vec in mass_map.items():
                if node_id not in node_by_id:
                    raise ValueError(f"mass node {node_id} not found")
                f.write(f"mass {node_id} {' '.join(str(v) for v in vec)}\n")

        # Materials (Elastic/Steel01/Steel02/Concrete01/Concrete02 uniaxial or ElasticIsotropic)
        for mat in materials.values():
            params = mat["params"]
            if mat["type"] == "Elastic":
                E = params["E"]
                f.write(f"uniaxialMaterial Elastic {mat['id']} {E}\n")
            elif mat["type"] == "Steel01":
                fy = params["Fy"]
                E0 = params["E0"]
                b = params["b"]
                f.write(f"uniaxialMaterial Steel01 {mat['id']} {fy} {E0} {b}\n")
            elif mat["type"] == "Steel02":
                fy = params["Fy"]
                E0 = params["E0"]
                b = params["b"]
                has_r = all(k in params for k in ("R0", "cR1", "cR2"))
                has_r_any = any(k in params for k in ("R0", "cR1", "cR2"))
                has_a = all(k in params for k in ("a1", "a2", "a3", "a4"))
                has_a_any = any(k in params for k in ("a1", "a2", "a3", "a4"))
                has_siginit = "sigInit" in params
                if has_r_any and not has_r:
                    raise ValueError("Steel02 requires R0, cR1, cR2 together")
                if has_a_any and not has_a:
                    raise ValueError("Steel02 requires a1, a2, a3, a4 together")
                if has_a and not has_r:
                    raise ValueError("Steel02 a1-a4 require R0/cR1/cR2")
                if has_siginit and not has_a:
                    raise ValueError("Steel02 sigInit requires a1-a4 and R0/cR1/cR2")
                if has_siginit:
                    f.write(
                        "uniaxialMaterial Steel02 "
                        f"{mat['id']} {fy} {E0} {b} "
                        f"{params['R0']} {params['cR1']} {params['cR2']} "
                        f"{params['a1']} {params['a2']} {params['a3']} {params['a4']} "
                        f"{params['sigInit']}\n"
                    )
                elif has_a:
                    f.write(
                        "uniaxialMaterial Steel02 "
                        f"{mat['id']} {fy} {E0} {b} "
                        f"{params['R0']} {params['cR1']} {params['cR2']} "
                        f"{params['a1']} {params['a2']} {params['a3']} {params['a4']}\n"
                    )
                elif has_r:
                    f.write(
                        "uniaxialMaterial Steel02 "
                        f"{mat['id']} {fy} {E0} {b} "
                        f"{params['R0']} {params['cR1']} {params['cR2']}\n"
                    )
                else:
                    f.write(f"uniaxialMaterial Steel02 {mat['id']} {fy} {E0} {b}\n")
            elif mat["type"] == "Concrete01":
                fpc = params["fpc"]
                epsc0 = params["epsc0"]
                fpcu = params["fpcu"]
                epscu = params["epscu"]
                f.write(
                    f"uniaxialMaterial Concrete01 {mat['id']} {fpc} {epsc0} {fpcu} {epscu}\n"
                )
            elif mat["type"] == "Concrete02":
                fpc = params["fpc"]
                epsc0 = params["epsc0"]
                fpcu = params["fpcu"]
                epscu = params["epscu"]
                has_rat = "rat" in params
                has_ft = "ft" in params
                has_ets = "Ets" in params
                if has_rat != has_ft or has_rat != has_ets:
                    raise ValueError("Concrete02 requires rat, ft, Ets together")
                if has_rat:
                    f.write(
                        "uniaxialMaterial Concrete02 "
                        f"{mat['id']} {fpc} {epsc0} {fpcu} {epscu} "
                        f"{params['rat']} {params['ft']} {params['Ets']}\n"
                    )
                else:
                    f.write(
                        f"uniaxialMaterial Concrete02 {mat['id']} {fpc} {epsc0} {fpcu} {epscu}\n"
                    )
            elif mat["type"] == "ElasticIsotropic":
                E = params["E"]
                nu = params["nu"]
                rho = params.get("rho", 0.0)
                f.write(f"nDMaterial ElasticIsotropic {mat['id']} {E} {nu} {rho}\n")
            else:
                raise ValueError(f"unsupported material type: {mat['type']}")

        # Sections (elastic, membrane/plate, or FiberSection2d subset)
        for sec in sections.values():
            params = sec["params"]
            if sec["type"] == "ElasticSection2d":
                E = params["E"]
                A = params["A"]
                I = params["I"]
                f.write(f"section Elastic {sec['id']} {E} {A} {I}\n")
            elif sec["type"] == "ElasticSection3d":
                E = params["E"]
                A = params["A"]
                Iz = params["Iz"]
                Iy = params["Iy"]
                G = params["G"]
                J = params["J"]
                f.write(f"section Elastic {sec['id']} {E} {A} {Iz} {Iy} {G} {J}\n")
            elif sec["type"] == "ElasticMembranePlateSection":
                E = params["E"]
                nu = params["nu"]
                h = params["h"]
                rho = params.get("rho", 0.0)
                f.write(
                    f"section ElasticMembranePlateSection {sec['id']} {E} {nu} {h} {rho}\n"
                )
            elif sec["type"] == "FiberSection2d":
                patches = params.get("patches", [])
                layers = params.get("layers", [])
                if not patches and not layers:
                    raise ValueError("FiberSection2d requires at least one patch or layer")
                f.write(f"section Fiber {sec['id']} {{\n")
                for patch in patches:
                    patch_type = patch.get("type")
                    if patch_type == "quad":
                        patch_type = "quadr"
                    mat = patch["material"]
                    if mat not in materials:
                        raise ValueError(f"FiberSection2d patch material {mat} not found")
                    if materials[mat]["type"] == "ElasticIsotropic":
                        raise ValueError(
                            "FiberSection2d patch requires uniaxial material (not ElasticIsotropic)"
                        )
                    ny = patch["num_subdiv_y"]
                    nz = patch["num_subdiv_z"]
                    if ny <= 0 or nz <= 0:
                        raise ValueError(
                            "FiberSection2d patch requires num_subdiv_y and num_subdiv_z > 0"
                        )
                    if patch_type == "rect":
                        yi = patch["y_i"]
                        zi = patch["z_i"]
                        yj = patch["y_j"]
                        zj = patch["z_j"]
                        f.write(
                            f"  patch rect {mat} {ny} {nz} {yi} {zi} {yj} {zj}\n"
                        )
                    elif patch_type == "quadr":
                        yi = patch["y_i"]
                        zi = patch["z_i"]
                        yj = patch["y_j"]
                        zj = patch["z_j"]
                        yk = patch["y_k"]
                        zk = patch["z_k"]
                        yl = patch["y_l"]
                        zl = patch["z_l"]
                        f.write(
                            "  patch quadr "
                            f"{mat} {ny} {nz} "
                            f"{yi} {zi} {yj} {zj} {yk} {zk} {yl} {zl}\n"
                        )
                    else:
                        raise ValueError(
                            f"unsupported FiberSection2d patch type: {patch_type}"
                        )
                for layer in layers:
                    layer_type = layer.get("type")
                    if layer_type != "straight":
                        raise ValueError(
                            f"unsupported FiberSection2d layer type: {layer_type}"
                        )
                    mat = layer["material"]
                    if mat not in materials:
                        raise ValueError(f"FiberSection2d layer material {mat} not found")
                    if materials[mat]["type"] == "ElasticIsotropic":
                        raise ValueError(
                            "FiberSection2d layer requires uniaxial material (not ElasticIsotropic)"
                        )
                    num_bars = layer["num_bars"]
                    bar_area = layer["bar_area"]
                    y_start = layer["y_start"]
                    z_start = layer["z_start"]
                    y_end = layer["y_end"]
                    z_end = layer["z_end"]
                    if num_bars <= 0:
                        raise ValueError(
                            "FiberSection2d layer straight requires num_bars > 0"
                        )
                    if bar_area <= 0:
                        raise ValueError(
                            "FiberSection2d layer straight requires bar_area > 0"
                        )
                    f.write(
                        "  layer straight "
                        f"{mat} {num_bars} {bar_area} "
                        f"{y_start} {z_start} {y_end} {z_end}\n"
                    )
                f.write("}\n")
            else:
                raise ValueError(f"unsupported section type: {sec['type']}")

        # Geometric transformations (only for beam-column elements)
        transf_tags = {}
        next_tag = 1
        for elem in elements:
            if elem["type"] not in (
                "elasticBeamColumn2d",
                "elasticBeamColumn3d",
                "forceBeamColumn2d",
                "dispBeamColumn2d",
                "nonlinearBeamColumn",
            ):
                continue
            name = elem.get("geomTransf", "Linear")
            if elem["type"] == "elasticBeamColumn3d":
                n1_id, n2_id = elem["nodes"]
                vecxz = _choose_vecxz(node_by_id[n1_id], node_by_id[n2_id])
                key = (name, vecxz)
            else:
                key = (name, None)
            if key not in transf_tags:
                transf_tags[key] = next_tag
                if key[1] is None:
                    f.write(f"geomTransf {name} {next_tag}\n")
                else:
                    vx, vy, vz = key[1]
                    f.write(f"geomTransf {name} {next_tag} {vx} {vy} {vz}\n")
                next_tag += 1

        # Beam integrations (forceBeamColumn2d/dispBeamColumn2d: Lobatto only)
        integration_tags = {}
        next_int_tag = 1
        for elem in elements:
            elem_type = elem["type"]
            if elem_type == "nonlinearBeamColumn":
                elem_type = "forceBeamColumn2d"
            if elem_type not in ("forceBeamColumn2d", "dispBeamColumn2d"):
                continue
            sec = sections[elem["section"]]
            if sec["type"] not in ("FiberSection2d", "ElasticSection2d"):
                raise ValueError(
                    f"{elem_type} requires FiberSection2d or ElasticSection2d"
                )
            geom = elem.get("geomTransf", "Linear")
            if geom not in ("Linear", "PDelta"):
                raise ValueError(f"{elem_type} supports geomTransf Linear or PDelta")
            integration = elem.get("integration", "Lobatto")
            if integration != "Lobatto":
                raise ValueError(f"{elem_type} supports Lobatto integration only")
            num_int_pts = int(elem.get("num_int_pts", 3))
            if num_int_pts not in (3, 5):
                raise ValueError(f"{elem_type} supports num_int_pts=3 or 5")
            key = (integration, elem["section"], num_int_pts)
            if key in integration_tags:
                continue
            integration_tags[key] = next_int_tag
            f.write(
                f"beamIntegration {integration} {next_int_tag} {elem['section']} {num_int_pts}\n"
            )
            next_int_tag += 1

        # Elements (elasticBeamColumn2d, truss, zeroLength, zeroLengthSection, twoNodeLink, fourNodeQuad/bbarQuad, shell)
        for elem in elements:
            if elem["type"] == "elasticBeamColumn2d":
                sec = sections[elem["section"]]
                if sec["type"] == "FiberSection2d":
                    raise ValueError(
                        "elasticBeamColumn2d with FiberSection2d requires "
                        "forceBeamColumn2d or dispBeamColumn2d"
                    )
                if sec["type"] != "ElasticSection2d":
                    raise ValueError("elasticBeamColumn2d requires ElasticSection2d")
                params = sec["params"]
                A = params["A"]
                E = params["E"]
                I = params["I"]
                n1, n2 = elem["nodes"]
                transf_tag = transf_tags[(elem.get("geomTransf", "Linear"), None)]
                f.write(
                    f"element elasticBeamColumn {elem['id']} {n1} {n2} {A} {E} {I} {transf_tag}\n"
                )
            elif elem["type"] in ("forceBeamColumn2d", "dispBeamColumn2d", "nonlinearBeamColumn"):
                elem_type = elem["type"]
                if elem_type == "nonlinearBeamColumn":
                    elem_type = "forceBeamColumn2d"
                sec = sections[elem["section"]]
                if sec["type"] not in ("FiberSection2d", "ElasticSection2d"):
                    raise ValueError(
                        f"{elem_type} requires FiberSection2d or ElasticSection2d"
                    )
                integration = elem.get("integration", "Lobatto")
                num_int_pts = int(elem.get("num_int_pts", 3))
                key = (integration, elem["section"], num_int_pts)
                if key not in integration_tags:
                    raise ValueError(f"{elem_type} integration definition missing")
                n1, n2 = elem["nodes"]
                transf_tag = transf_tags[(elem.get("geomTransf", "Linear"), None)]
                int_tag = integration_tags[key]
                element_cmd = "forceBeamColumn"
                if elem_type == "dispBeamColumn2d":
                    element_cmd = "dispBeamColumn"
                f.write(
                    f"element {element_cmd} {elem['id']} {n1} {n2} {transf_tag} {int_tag}\n"
                )
            elif elem["type"] == "elasticBeamColumn3d":
                sec = sections[elem["section"]]
                if sec["type"] != "ElasticSection3d":
                    raise ValueError("elasticBeamColumn3d requires ElasticSection3d")
                params = sec["params"]
                A = params["A"]
                E = params["E"]
                G = params["G"]
                J = params["J"]
                Iy = params["Iy"]
                Iz = params["Iz"]
                n1, n2 = elem["nodes"]
                vecxz = _choose_vecxz(node_by_id[n1], node_by_id[n2])
                transf_tag = transf_tags[(elem.get("geomTransf", "Linear"), vecxz)]
                f.write(
                    f"element elasticBeamColumn {elem['id']} {n1} {n2} {A} {E} {G} {J} {Iy} {Iz} {transf_tag}\n"
                )
            elif elem["type"] == "truss":
                n1, n2 = elem["nodes"]
                area = elem["area"]
                mat_id = elem["material"]
                f.write(f"element truss {elem['id']} {n1} {n2} {area} {mat_id}\n")
            elif elem["type"] == "zeroLength":
                n1, n2 = elem["nodes"]
                mats = " ".join(str(mid) for mid in elem["materials"])
                dirs = " ".join(str(d) for d in elem["dirs"])
                f.write(f"element zeroLength {elem['id']} {n1} {n2} -mat {mats} -dir {dirs}\n")
            elif elem["type"] == "zeroLengthSection":
                n1, n2 = elem["nodes"]
                sec_id = elem["section"]
                if sec_id not in sections:
                    raise ValueError("zeroLengthSection section not found")
                sec_type = sections[sec_id]["type"]
                if sec_type not in ("FiberSection2d", "ElasticSection2d"):
                    raise ValueError(
                        "zeroLengthSection requires FiberSection2d or ElasticSection2d"
                    )
                f.write(f"element zeroLengthSection {elem['id']} {n1} {n2} {sec_id}\n")
            elif elem["type"] == "twoNodeLink":
                n1, n2 = elem["nodes"]
                mats = " ".join(str(mid) for mid in elem["materials"])
                dirs = " ".join(str(d) for d in elem["dirs"])
                f.write(f"element twoNodeLink {elem['id']} {n1} {n2} -mat {mats} -dir {dirs}\n")
            elif elem["type"] == "fourNodeQuad" or elem["type"] == "bbarQuad":
                n1, n2, n3, n4 = elem["nodes"]
                t = elem["thickness"]
                mat_id = elem["material"]
                formulation = elem.get("formulation", "PlaneStress")
                f.write(
                    f"element quad {elem['id']} {n1} {n2} {n3} {n4} {t} \"{formulation}\" {mat_id}\n"
                )
            elif elem["type"] == "shell":
                n1, n2, n3, n4 = elem["nodes"]
                sec_id = elem["section"]
                f.write(f"element shell {elem['id']} {n1} {n2} {n3} {n4} {sec_id}\n")
            else:
                raise ValueError(f"unsupported element type: {elem['type']}")

        # Loads / patterns (Plain or UniformExcitation)
        loads = data.get("loads", [])
        element_loads = data.get("element_loads", [])
        pattern = data.get("pattern")
        ts_tags = set()
        if loads or element_loads or pattern is not None:
            ts_list = _normalize_time_series(data.get("time_series"))
            if ts_list:
                for ts in ts_list:
                    _emit_time_series(f, ts, case_dir, data)
                ts_tags = {ts["tag"] for ts in ts_list}
                if pattern is None:
                    if len(ts_list) == 1:
                        pattern = {"type": "Plain", "tag": 1, "time_series": ts_list[0]["tag"]}
                    else:
                        raise ValueError("pattern required when multiple time_series are defined")
            else:
                pattern_type = pattern.get("type", "Plain") if pattern is not None else "Plain"
                if pattern_type == "UniformExcitation":
                    raise ValueError("UniformExcitation pattern requires time_series definitions")
                if loads or element_loads:
                    _emit_time_series(
                        f, {"type": "Linear", "tag": 1, "factor": 1.0}, case_dir, data
                    )
                    ts_tags = {1}
                    if pattern is None:
                        pattern = {"type": "Plain", "tag": 1, "time_series": 1}

            if pattern is None:
                raise ValueError("pattern required when loads are present")
            pattern_type = pattern.get("type", "Plain")
            if pattern_type == "Plain":
                pattern_tag = pattern.get("tag", 1)
                ts_tag = pattern.get("time_series")
                if ts_tag is None:
                    raise ValueError("pattern missing time_series tag")
                if ts_tag not in ts_tags:
                    raise ValueError(f"pattern time_series tag {ts_tag} not found")
                f.write(f"pattern Plain {pattern_tag} {ts_tag} {{\n")
                if loads:
                    load_map = {}
                    for load in loads:
                        node_id = load["node"]
                        vec = load_map.setdefault(node_id, [0.0] * ndf)
                        dof = load["dof"]
                        if dof < 1 or dof > ndf:
                            raise ValueError(f"load dof {dof} out of range 1..{ndf}")
                        vec[dof - 1] += load["value"]
                    for node_id, vec in load_map.items():
                        f.write(f"  load {node_id} {' '.join(str(v) for v in vec)}\n")
                for elem_load in element_loads:
                    if elem_load["type"] != "beamUniform":
                        raise ValueError(f"unsupported element load type: {elem_load['type']}")
                    elem_id = elem_load["element"]
                    wy = elem_load.get("wy", elem_load.get("w", 0.0))
                    if "wx" in elem_load:
                        wx = elem_load["wx"]
                        f.write(f"  eleLoad -ele {elem_id} -type -beamUniform {wy} {wx}\n")
                    else:
                        f.write(f"  eleLoad -ele {elem_id} -type -beamUniform {wy}\n")
                f.write("}\n")
            elif pattern_type == "UniformExcitation":
                if loads or element_loads:
                    raise ValueError("UniformExcitation does not support nodal/element loads")
                pattern_tag = pattern.get("tag", 1)
                direction = pattern.get("direction")
                if direction is None:
                    raise ValueError("UniformExcitation pattern missing direction")
                direction = int(direction)
                if direction < 1 or direction > ndm:
                    raise ValueError("UniformExcitation direction out of range 1..ndm")
                accel_tag = pattern.get("accel", pattern.get("time_series"))
                if accel_tag is None:
                    raise ValueError("UniformExcitation pattern missing accel time_series tag")
                accel_tag = int(accel_tag)
                if accel_tag not in ts_tags:
                    raise ValueError(
                        f"UniformExcitation accel time_series tag {accel_tag} not found"
                    )
                f.write(
                    f"pattern UniformExcitation {pattern_tag} {direction} -accel {accel_tag}\n"
                )
            else:
                raise ValueError(f"unsupported pattern type: {pattern_type}")

        rayleigh = data.get("rayleigh")
        if rayleigh is not None:
            alpha_m = float(rayleigh.get("alphaM", 0.0))
            beta_k = float(rayleigh.get("betaK", 0.0))
            beta_k_init = float(rayleigh.get("betaKInit", 0.0))
            beta_k_comm = float(rayleigh.get("betaKComm", 0.0))
            f.write(f"rayleigh {alpha_m} {beta_k} {beta_k_init} {beta_k_comm}\n")

        # Analysis setup
        analysis = data.get("analysis", {"type": "static_linear", "steps": 1})
        analysis_type = analysis.get("type", "static_linear")
        steps = analysis.get("steps", 1)
        constraints_handler = analysis.get("constraints", "Plain")
        dt = None
        static_nl_post_lines = None
        transient_nonlinear_emits_analyze = True

        if analysis_type == "staged":
            stages = analysis.get("stages", [])
            if not isinstance(stages, list) or len(stages) == 0:
                raise ValueError("staged analysis requires non-empty analysis.stages")
            if constraints_handler not in ("Plain", "Transformation"):
                raise ValueError(f"unsupported constraints handler: {constraints_handler}")
            if mp_constraints and constraints_handler != "Transformation":
                raise ValueError("mp_constraints require analysis.constraints=Transformation")

            _emit_recorders(f, recorders, node_by_id, ndf)

            for stage_idx, stage in enumerate(stages):
                if not isinstance(stage, dict):
                    raise ValueError("analysis.stages entries must be objects")
                stage_analysis = stage.get("analysis", stage)
                if not isinstance(stage_analysis, dict):
                    raise ValueError("analysis.stages[].analysis must be an object")
                stage_type = stage_analysis.get("type")
                if stage_type is None:
                    raise ValueError("analysis.stages[].analysis missing type")

                stage_ts_list = _normalize_time_series(stage.get("time_series"))
                for ts in stage_ts_list:
                    _emit_time_series(f, ts, case_dir, data)
                    ts_tags.add(ts["tag"])

                stage_pattern = stage.get("pattern")
                stage_loads = stage.get("loads", loads if stage_idx == 0 else [])
                stage_element_loads = stage.get(
                    "element_loads",
                    element_loads if stage_idx == 0 else [],
                )
                if stage_pattern is not None:
                    stage_pattern_type = stage_pattern.get("type", "Plain")
                    if stage_pattern_type == "Plain":
                        pattern_tag = stage_pattern.get("tag", 1)
                        ts_tag = stage_pattern.get("time_series")
                        if ts_tag is None:
                            raise ValueError("pattern missing time_series tag")
                        if ts_tag not in ts_tags:
                            raise ValueError(f"pattern time_series tag {ts_tag} not found")
                        f.write(f"pattern Plain {pattern_tag} {ts_tag} {{\n")
                        if stage_loads:
                            load_map = {}
                            for load in stage_loads:
                                node_id = load["node"]
                                vec = load_map.setdefault(node_id, [0.0] * ndf)
                                dof = load["dof"]
                                if dof < 1 or dof > ndf:
                                    raise ValueError(f"load dof {dof} out of range 1..{ndf}")
                                vec[dof - 1] += load["value"]
                            for node_id, vec in load_map.items():
                                f.write(f"  load {node_id} {' '.join(str(v) for v in vec)}\n")
                        for elem_load in stage_element_loads:
                            if elem_load["type"] != "beamUniform":
                                raise ValueError(
                                    f"unsupported element load type: {elem_load['type']}"
                                )
                            elem_id = elem_load["element"]
                            wy = elem_load.get("wy", elem_load.get("w", 0.0))
                            if "wx" in elem_load:
                                wx = elem_load["wx"]
                                f.write(
                                    f"  eleLoad -ele {elem_id} -type -beamUniform {wy} {wx}\n"
                                )
                            else:
                                f.write(f"  eleLoad -ele {elem_id} -type -beamUniform {wy}\n")
                        f.write("}\n")
                    elif stage_pattern_type == "UniformExcitation":
                        if stage_loads or stage_element_loads:
                            raise ValueError(
                                "UniformExcitation does not support nodal/element loads"
                            )
                        pattern_tag = stage_pattern.get("tag", 1)
                        direction = stage_pattern.get("direction")
                        if direction is None:
                            raise ValueError("UniformExcitation pattern missing direction")
                        direction = int(direction)
                        if direction < 1 or direction > ndm:
                            raise ValueError(
                                "UniformExcitation direction out of range 1..ndm"
                            )
                        accel_tag = stage_pattern.get(
                            "accel", stage_pattern.get("time_series")
                        )
                        if accel_tag is None:
                            raise ValueError(
                                "UniformExcitation pattern missing accel time_series tag"
                            )
                        accel_tag = int(accel_tag)
                        if accel_tag not in ts_tags:
                            raise ValueError(
                                f"UniformExcitation accel time_series tag {accel_tag} not found"
                            )
                        f.write(
                            f"pattern UniformExcitation {pattern_tag} {direction} -accel {accel_tag}\n"
                        )
                    else:
                        raise ValueError(
                            f"unsupported staged pattern type: {stage_pattern_type}"
                        )
                elif stage_idx > 0 and (stage_loads or stage_element_loads):
                    raise ValueError(
                        "staged analysis stage loads require an explicit stage pattern"
                    )

                stage_rayleigh = stage.get("rayleigh")
                if stage_rayleigh is not None:
                    alpha_m = float(stage_rayleigh.get("alphaM", 0.0))
                    beta_k = float(stage_rayleigh.get("betaK", 0.0))
                    beta_k_init = float(stage_rayleigh.get("betaKInit", 0.0))
                    beta_k_comm = float(stage_rayleigh.get("betaKComm", 0.0))
                    f.write(f"rayleigh {alpha_m} {beta_k} {beta_k_init} {beta_k_comm}\n")

                stage_constraints = stage_analysis.get("constraints", constraints_handler)
                if stage_constraints not in ("Plain", "Transformation"):
                    raise ValueError(
                        f"unsupported constraints handler: {stage_constraints}"
                    )
                f.write(f"constraints {stage_constraints}\n")
                f.write("numberer RCM\n")
                f.write("system BandGeneral\n")

                stage_steps = int(stage_analysis.get("steps", 1))
                if stage_steps < 1:
                    raise ValueError("analysis steps must be >= 1")
                stage_dt = None
                stage_static_nl_post_lines = None
                stage_transient_nl_emits_analyze = True
                if stage_type == "static_linear":
                    f.write("test NormUnbalance 1.0e-12 10\n")
                    f.write("algorithm Linear\n")
                    f.write("integrator LoadControl 1.0\n")
                    f.write("analysis Static\n")
                elif stage_type == "static_nonlinear":
                    tol = stage_analysis.get("tol", 1.0e-10)
                    max_iters = stage_analysis.get("max_iters", 20)
                    algorithm = stage_analysis.get("algorithm", "Newton")
                    if algorithm not in ("Newton", "ModifiedNewton"):
                        raise ValueError(
                            f"unsupported static_nonlinear algorithm: {algorithm}"
                        )
                    f.write(f"test NormUnbalance {tol} {max_iters}\n")
                    f.write(f"algorithm {algorithm}\n")
                    integrator = stage_analysis.get("integrator", {"type": "LoadControl"})
                    integrator_type = integrator.get("type", "LoadControl")
                    if integrator_type == "LoadControl":
                        f.write(f"integrator LoadControl {1.0/stage_steps}\n")
                        f.write("analysis Static\n")
                    elif integrator_type == "DisplacementControl":
                        node = integrator.get("node")
                        dof = integrator.get("dof")
                        if node is None or dof is None:
                            raise ValueError("DisplacementControl requires node and dof")
                        f.write("analysis Static\n")
                        targets = integrator.get("targets")
                        if targets is not None:
                            if not isinstance(targets, list) or len(targets) == 0:
                                raise ValueError(
                                    "DisplacementControl targets must be a non-empty list"
                                )
                            stage_static_nl_post_lines = [
                                "set strut_dc_prev 0.0",
                                "set strut_dc_targets {"
                                + " ".join(str(float(val)) for val in targets)
                                + "}",
                                "foreach strut_dc_targ $strut_dc_targets {",
                                "  set strut_dc_du [expr $strut_dc_targ - $strut_dc_prev]",
                                "  if {[expr abs($strut_dc_du)] < 1.0e-16} {",
                                "    set strut_dc_prev $strut_dc_targ",
                                "    continue",
                                "  }",
                                f"  integrator DisplacementControl {int(node)} {int(dof)} $strut_dc_du",
                                "  set strut_dc_ok [analyze 1]",
                                "  if {$strut_dc_ok != 0} {",
                                "    error \"analysis failed\"",
                                "  }",
                                "  set strut_dc_prev $strut_dc_targ",
                                "}",
                            ]
                        else:
                            du = integrator.get("du")
                            if du is None or float(du) == 0.0:
                                raise ValueError(
                                    "DisplacementControl requires non-zero du when targets are omitted"
                                )
                            f.write(
                                f"integrator DisplacementControl {int(node)} {int(dof)} {float(du)}\n"
                            )
                            stage_static_nl_post_lines = [
                                f"set strut_nl_ok [analyze {stage_steps}]",
                                "if {$strut_nl_ok != 0} {",
                                "  error \"analysis failed\"",
                                "}",
                            ]
                    else:
                        raise ValueError(
                            f"unsupported static_nonlinear integrator: {integrator_type}"
                        )
                elif stage_type == "transient_linear":
                    stage_dt = stage_analysis.get("dt")
                    if stage_dt is None or stage_dt <= 0.0:
                        raise ValueError("transient_linear requires dt > 0")
                    integrator = stage_analysis.get("integrator", {"type": "Newmark"})
                    if integrator.get("type", "Newmark") != "Newmark":
                        raise ValueError("transient_linear only supports Newmark integrator")
                    gamma = integrator.get("gamma", 0.5)
                    beta = integrator.get("beta", 0.25)
                    f.write("test NormUnbalance 1.0e-12 10\n")
                    f.write("algorithm Linear\n")
                    f.write(f"integrator Newmark {gamma} {beta}\n")
                    f.write("analysis Transient\n")
                elif stage_type == "transient_nonlinear":
                    stage_dt = stage_analysis.get("dt")
                    if stage_dt is None or stage_dt <= 0.0:
                        raise ValueError("transient_nonlinear requires dt > 0")
                    algorithm = stage_analysis.get("algorithm", "Newton")
                    if algorithm not in (
                        "Newton",
                        "ModifiedNewton",
                        "ModifiedNewtonInitial",
                        "Broyden",
                        "NewtonLineSearch",
                    ):
                        raise ValueError(
                            f"unsupported transient_nonlinear algorithm: {algorithm}"
                        )
                    fallback_algorithm = stage_analysis.get("fallback_algorithm")
                    if fallback_algorithm is not None and fallback_algorithm not in (
                        "Newton",
                        "ModifiedNewton",
                        "ModifiedNewtonInitial",
                        "Broyden",
                        "NewtonLineSearch",
                    ):
                        raise ValueError(
                            "unsupported transient_nonlinear fallback_algorithm: "
                            f"{fallback_algorithm}"
                        )
                    integrator = stage_analysis.get("integrator", {"type": "Newmark"})
                    if integrator.get("type", "Newmark") != "Newmark":
                        raise ValueError(
                            "transient_nonlinear only supports Newmark integrator"
                        )
                    gamma = integrator.get("gamma", 0.5)
                    beta = integrator.get("beta", 0.25)
                    test_type = stage_analysis.get("test_type", "NormUnbalance")
                    if test_type not in ("NormUnbalance", "NormDispIncr", "EnergyIncr"):
                        raise ValueError(
                            "transient_nonlinear test_type must be NormUnbalance, NormDispIncr, or EnergyIncr"
                        )
                    tol = stage_analysis.get("tol", 1.0e-10)
                    max_iters = stage_analysis.get("max_iters", 20)
                    primary_algorithm = _algorithm_cmd(algorithm, stage_analysis)
                    f.write(f"test {test_type} {tol} {max_iters}\n")
                    f.write(f"algorithm {primary_algorithm}\n")
                    f.write(f"integrator Newmark {gamma} {beta}\n")
                    f.write("analysis Transient\n")
                    if fallback_algorithm is not None:
                        fallback_test_type = stage_analysis.get(
                            "fallback_test_type", test_type
                        )
                        if fallback_test_type not in (
                            "NormUnbalance",
                            "NormDispIncr",
                            "EnergyIncr",
                        ):
                            raise ValueError(
                                "transient_nonlinear fallback_test_type must be NormUnbalance, NormDispIncr, or EnergyIncr"
                            )
                        fallback_tol = stage_analysis.get("fallback_tol", tol)
                        fallback_max_iters = stage_analysis.get(
                            "fallback_max_iters", max_iters
                        )
                        fallback_algorithm_cmd = _algorithm_cmd(
                            fallback_algorithm,
                            stage_analysis,
                            prefix="fallback_",
                        )
                        f.write("set strut_tr_ok 0\n")
                        f.write(
                            f"for {{set strut_tr_step 0}} {{$strut_tr_step < {stage_steps} && $strut_tr_ok == 0}} {{incr strut_tr_step}} {{\n"
                        )
                        f.write(f"  set strut_tr_ok [analyze 1 {stage_dt}]\n")
                        f.write("  if {$strut_tr_ok != 0} {\n")
                        f.write(
                            f"    test {fallback_test_type} {fallback_tol} {fallback_max_iters}\n"
                        )
                        f.write(f"    algorithm {fallback_algorithm_cmd}\n")
                        f.write(f"    set strut_tr_ok [analyze 1 {stage_dt}]\n")
                        f.write(f"    test {test_type} {tol} {max_iters}\n")
                        f.write(f"    algorithm {primary_algorithm}\n")
                        f.write("  }\n")
                        f.write("}\n")
                        f.write("if {$strut_tr_ok != 0} {\n")
                        f.write("  error \"analysis failed\"\n")
                        f.write("}\n")
                        stage_transient_nl_emits_analyze = False
                elif stage_type == "modal_eigen":
                    num_modes = int(stage_analysis.get("num_modes", 0))
                    if num_modes < 1:
                        raise ValueError("modal_eigen requires num_modes >= 1")
                else:
                    raise ValueError(
                        f"unsupported staged analysis type: {stage_type}"
                    )

                if stage_type == "transient_linear" or (
                    stage_type == "transient_nonlinear"
                    and stage_transient_nl_emits_analyze
                ):
                    f.write(f"analyze {stage_steps} {stage_dt}\n")
                elif stage_type == "modal_eigen":
                    num_modes = int(stage_analysis.get("num_modes", 0))
                    f.write(f"set strut_modal_lambda [eigen {num_modes}]\n")
                elif stage_type == "static_nonlinear":
                    integrator = stage_analysis.get("integrator", {"type": "LoadControl"})
                    if integrator.get("type", "LoadControl") == "LoadControl":
                        f.write(f"set strut_nl_ok [analyze {stage_steps}]\n")
                        f.write("if {$strut_nl_ok != 0} {\n")
                        f.write("  error \"analysis failed\"\n")
                        f.write("}\n")
                    elif stage_static_nl_post_lines is not None:
                        for line in stage_static_nl_post_lines:
                            f.write(line + "\n")
                elif stage_type == "transient_nonlinear":
                    # The staged transient_nonlinear branch above either emitted a single
                    # `analyze` or a per-step fallback loop.
                    pass
                else:
                    f.write(f"analyze {stage_steps}\n")

                load_const = stage.get("load_const")
                if load_const is not None and load_const is not False:
                    if isinstance(load_const, dict):
                        lc_time = float(load_const.get("time", 0.0))
                    elif isinstance(load_const, bool):
                        lc_time = 0.0
                    else:
                        lc_time = float(load_const)
                    f.write(f"loadConst -time {lc_time}\n")
            return

        if steps < 1:
            raise ValueError("analysis steps must be >= 1")
        if constraints_handler not in ("Plain", "Transformation"):
            raise ValueError(f"unsupported constraints handler: {constraints_handler}")
        if mp_constraints and constraints_handler != "Transformation":
            raise ValueError("mp_constraints require analysis.constraints=Transformation")
        f.write(f"constraints {constraints_handler}\n")
        f.write("numberer RCM\n")
        f.write("system BandGeneral\n")
        if analysis_type == "static_linear":
            f.write("test NormUnbalance 1.0e-12 10\n")
            f.write("algorithm Linear\n")
            f.write("integrator LoadControl 1.0\n")
            f.write("analysis Static\n")
        elif analysis_type == "static_nonlinear":
            tol = analysis.get("tol", 1.0e-10)
            max_iters = analysis.get("max_iters", 20)
            algorithm = analysis.get("algorithm", "Newton")
            if algorithm not in ("Newton", "ModifiedNewton"):
                raise ValueError(
                    f"unsupported static_nonlinear algorithm: {algorithm}"
                )
            f.write(f"test NormUnbalance {tol} {max_iters}\n")
            f.write(f"algorithm {algorithm}\n")
            integrator = analysis.get("integrator", {"type": "LoadControl"})
            integrator_type = integrator.get("type", "LoadControl")
            if integrator_type == "LoadControl":
                f.write(f"integrator LoadControl {1.0/steps}\n")
                f.write("analysis Static\n")
            elif integrator_type == "DisplacementControl":
                node = integrator.get("node")
                dof = integrator.get("dof")
                if node is None or dof is None:
                    raise ValueError("DisplacementControl requires node and dof")
                f.write("analysis Static\n")
                targets = integrator.get("targets")
                if targets is not None:
                    if not isinstance(targets, list) or len(targets) == 0:
                        raise ValueError("DisplacementControl targets must be a non-empty list")
                    static_nl_post_lines = [
                        "set strut_dc_prev 0.0",
                        "set strut_dc_targets {" + " ".join(str(float(val)) for val in targets) + "}",
                        "foreach strut_dc_targ $strut_dc_targets {",
                        "  set strut_dc_du [expr $strut_dc_targ - $strut_dc_prev]",
                        "  if {[expr abs($strut_dc_du)] < 1.0e-16} {",
                        "    set strut_dc_prev $strut_dc_targ",
                        "    continue",
                        "  }",
                        f"  integrator DisplacementControl {int(node)} {int(dof)} $strut_dc_du",
                        "  set strut_dc_ok [analyze 1]",
                        "  if {$strut_dc_ok != 0} {",
                        "    error \"analysis failed\"",
                        "  }",
                        "  set strut_dc_prev $strut_dc_targ",
                        "}",
                    ]
                else:
                    du = integrator.get("du")
                    if du is None or float(du) == 0.0:
                        raise ValueError("DisplacementControl requires non-zero du when targets are omitted")
                    f.write(f"integrator DisplacementControl {int(node)} {int(dof)} {float(du)}\n")
                    static_nl_post_lines = [
                        f"set strut_dc_ok [analyze {steps}]",
                        "if {$strut_dc_ok != 0} {",
                        "  error \"analysis failed\"",
                        "}",
                    ]
            else:
                raise ValueError(f"unsupported static_nonlinear integrator: {integrator_type}")
        elif analysis_type == "transient_linear":
            dt = analysis.get("dt")
            if dt is None or dt <= 0.0:
                raise ValueError("transient_linear requires dt > 0")
            integrator = analysis.get("integrator", {"type": "Newmark"})
            if integrator.get("type", "Newmark") != "Newmark":
                raise ValueError("transient_linear only supports Newmark integrator")
            gamma = integrator.get("gamma", 0.5)
            beta = integrator.get("beta", 0.25)
            f.write("test NormUnbalance 1.0e-12 10\n")
            f.write("algorithm Linear\n")
            f.write(f"integrator Newmark {gamma} {beta}\n")
            f.write("analysis Transient\n")
        elif analysis_type == "transient_nonlinear":
            dt = analysis.get("dt")
            if dt is None or dt <= 0.0:
                raise ValueError("transient_nonlinear requires dt > 0")
            algorithm = analysis.get("algorithm", "Newton")
            if algorithm not in (
                "Newton",
                "ModifiedNewton",
                "ModifiedNewtonInitial",
                "Broyden",
                "NewtonLineSearch",
            ):
                raise ValueError(
                    f"unsupported transient_nonlinear algorithm: {algorithm}"
                )
            fallback_algorithm = analysis.get("fallback_algorithm")
            if fallback_algorithm is not None and fallback_algorithm not in (
                "Newton",
                "ModifiedNewton",
                "ModifiedNewtonInitial",
                "Broyden",
                "NewtonLineSearch",
            ):
                raise ValueError(
                    f"unsupported transient_nonlinear fallback_algorithm: {fallback_algorithm}"
                )
            integrator = analysis.get("integrator", {"type": "Newmark"})
            if integrator.get("type", "Newmark") != "Newmark":
                raise ValueError("transient_nonlinear only supports Newmark integrator")
            gamma = integrator.get("gamma", 0.5)
            beta = integrator.get("beta", 0.25)
            test_type = analysis.get("test_type", "NormUnbalance")
            if test_type not in ("NormUnbalance", "NormDispIncr", "EnergyIncr"):
                raise ValueError(
                    "transient_nonlinear test_type must be NormUnbalance, NormDispIncr, or EnergyIncr"
                )
            tol = analysis.get("tol", 1.0e-10)
            max_iters = analysis.get("max_iters", 20)
            primary_algorithm = _algorithm_cmd(algorithm, analysis)
            f.write(f"test {test_type} {tol} {max_iters}\n")
            f.write(f"algorithm {primary_algorithm}\n")
            f.write(f"integrator Newmark {gamma} {beta}\n")
            f.write("analysis Transient\n")
            if fallback_algorithm is not None:
                fallback_test_type = analysis.get("fallback_test_type", test_type)
                if fallback_test_type not in (
                    "NormUnbalance",
                    "NormDispIncr",
                    "EnergyIncr",
                ):
                    raise ValueError(
                        "transient_nonlinear fallback_test_type must be NormUnbalance, NormDispIncr, or EnergyIncr"
                    )
                fallback_tol = analysis.get("fallback_tol", tol)
                fallback_max_iters = analysis.get("fallback_max_iters", max_iters)
                fallback_algorithm_cmd = _algorithm_cmd(
                    fallback_algorithm,
                    analysis,
                    prefix="fallback_",
                )
                f.write("set strut_tr_ok 0\n")
                f.write(
                    f"for {{set strut_tr_step 0}} {{$strut_tr_step < {int(steps)} && $strut_tr_ok == 0}} {{incr strut_tr_step}} {{\n"
                )
                f.write(f"  set strut_tr_ok [analyze 1 {dt}]\n")
                f.write("  if {$strut_tr_ok != 0} {\n")
                f.write(f"    test {fallback_test_type} {fallback_tol} {fallback_max_iters}\n")
                f.write(f"    algorithm {fallback_algorithm_cmd}\n")
                f.write(f"    set strut_tr_ok [analyze 1 {dt}]\n")
                f.write(f"    test {test_type} {tol} {max_iters}\n")
                f.write(f"    algorithm {primary_algorithm}\n")
                f.write("  }\n")
                f.write("}\n")
                f.write("if {$strut_tr_ok != 0} {\n")
                f.write("  error \"analysis failed\"\n")
                f.write("}\n")
                transient_nonlinear_emits_analyze = False
        elif analysis_type == "modal_eigen":
            num_modes = int(analysis.get("num_modes", 0))
            if num_modes < 1:
                raise ValueError("modal_eigen requires num_modes >= 1")
        else:
            raise ValueError(f"unsupported analysis type: {analysis_type}")

        # Recorders
        _emit_recorders(f, recorders, node_by_id, ndf)

        if analysis_type == "transient_linear" or (
            analysis_type == "transient_nonlinear" and transient_nonlinear_emits_analyze
        ):
            f.write(f"analyze {steps} {dt}\n")
        elif analysis_type == "modal_eigen":
            num_modes = int(analysis.get("num_modes", 0))
            f.write(f"set strut_modal_lambda [eigen {num_modes}]\n")
            modal_outputs = {}
            for rec in recorders:
                if rec.get("type") != "modal_eigen":
                    continue
                output = rec.get("output", "modal")
                if output not in modal_outputs:
                    modal_outputs[output] = rec
                    f.write(f"set strut_ev_file [open \"{output}_eigenvalues.out\" \"w\"]\n")
                    f.write("foreach strut_ev $strut_modal_lambda {\n")
                    f.write("  puts $strut_ev_file $strut_ev\n")
                    f.write("}\n")
                    f.write("close $strut_ev_file\n")

                modes = rec.get("modes", [])
                if not isinstance(modes, list) or len(modes) == 0:
                    raise ValueError("modal_eigen recorder requires non-empty modes")
                nodes_out = rec.get("nodes", [])
                dofs = rec.get("dofs", [])
                if not isinstance(nodes_out, list) or len(nodes_out) == 0:
                    raise ValueError("modal_eigen recorder requires non-empty nodes")
                if not isinstance(dofs, list) or len(dofs) == 0:
                    raise ValueError("modal_eigen recorder requires non-empty dofs")
                for mode in modes:
                    mode_no = int(mode)
                    if mode_no < 1 or mode_no > num_modes:
                        raise ValueError("modal_eigen recorder mode out of range")
                    for node_id in nodes_out:
                        if node_id not in node_by_id:
                            raise ValueError(f"modal_eigen recorder node {node_id} not found")
                        f.write("set strut_modal_line \"\"\n")
                        for dof in dofs:
                            if dof < 1 or dof > ndf:
                                raise ValueError(f"modal_eigen dof {dof} out of range 1..{ndf}")
                            f.write(
                                f"append strut_modal_line \"[nodeEigenvector {int(node_id)} {mode_no} {int(dof)}] \"\n"
                            )
                        f.write(
                            f"set strut_modal_file [open \"{output}_mode{mode_no}_node{int(node_id)}.out\" \"w\"]\n"
                        )
                        f.write("puts $strut_modal_file [string trim $strut_modal_line]\n")
                        f.write("close $strut_modal_file\n")
        elif analysis_type == "static_nonlinear":
            integrator = analysis.get("integrator", {"type": "LoadControl"})
            if integrator.get("type", "LoadControl") == "LoadControl":
                f.write(f"set strut_nl_ok [analyze {steps}]\n")
                f.write("if {$strut_nl_ok != 0} {\n")
                f.write("  error \"analysis failed\"\n")
                f.write("}\n")
            elif static_nl_post_lines is not None:
                for line in static_nl_post_lines:
                    f.write(line + "\n")
        else:
            f.write(f"analyze {steps}\n")


if __name__ == "__main__":
    main()
