#!/usr/bin/env python3
import argparse
import json
import math
import re
from pathlib import Path

def _constraints_to_fix(ndf, constraints):
    if constraints is None:
        return None
    if isinstance(constraints, list):
        if constraints and all(isinstance(v, bool) for v in constraints):
            if len(constraints) != ndf:
                raise ValueError(f"constraints bool list length {len(constraints)} != ndf {ndf}")
            return [1 if v else 0 for v in constraints]
        # assume list of 1-based dof indices
        fix = [0] * ndf
        for dof in constraints:
            if not isinstance(dof, int):
                raise ValueError("constraints must be list of ints or bools")
            if dof < 1 or dof > ndf:
                raise ValueError(f"constraint dof {dof} out of range 1..{ndf}")
            fix[dof - 1] = 1
        return fix
    raise ValueError("constraints must be list")


def _write_header(f):
    f.write("# Auto-generated by json_to_tcl.py\n")


def _require_field(obj, key):
    if key not in obj:
        raise ValueError(f"missing required field: {key}")
    return obj[key]


def _choose_vecxz(n1, n2):
    dx = n2["x"] - n1["x"]
    dy = n2["y"] - n1["y"]
    dz = n2["z"] - n1["z"]
    length = math.sqrt(dx * dx + dy * dy + dz * dz)
    if length == 0.0:
        raise ValueError("zero-length element")
    ax = dx / length
    ay = dy / length
    az = dz / length

    candidates = ((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0))
    for vx, vy, vz in candidates:
        dot = abs(ax * vx + ay * vy + az * vz)
        if dot < 0.9:
            return (vx, vy, vz)
    return (1.0, 0.0, 0.0)


def _choose_ref_y_from_x(xvec):
    ax, ay, az = xvec
    candidates = ((0.0, 1.0, 0.0), (1.0, 0.0, 0.0), (0.0, 0.0, 1.0))
    for vy in candidates:
        dot = abs(ax * vy[0] + ay * vy[1] + az * vy[2])
        if dot < 0.9:
            return vy
    return (0.0, 1.0, 0.0)


def _format_link_orient(elem, ndm):
    orient = elem.get("orient")
    if not orient:
        return ""
    xvec = orient.get("x")
    yvec = orient.get("y")
    if xvec is None and yvec is None:
        return ""
    if ndm == 2:
        if xvec is None:
            raise ValueError("2D link orientation requires orient.x")
        if len(xvec) != 3:
            raise ValueError("2D link orient.x must have 3 values")
        return f" -orient {_format_list(xvec)}"
    if xvec is None:
        raise ValueError("3D link orientation currently requires orient.x")
    if len(xvec) != 3:
        raise ValueError("3D link orient.x must have 3 values")
    if yvec is None:
        yvec = _choose_ref_y_from_x(xvec)
    if len(yvec) != 3:
        raise ValueError("3D link orient.y must have 3 values")
    return f" -orient {_format_list(xvec)} {_format_list(yvec)}"


_BEAM_INTEGRATION_MIN_POINTS = {
    "Lobatto": 2,
    "Legendre": 1,
    "Radau": 1,
}


def _validate_beam_integration(elem_type, integration, num_int_pts):
    if integration not in _BEAM_INTEGRATION_MIN_POINTS:
        raise ValueError(
            f"{elem_type} supports integration Lobatto, Legendre, or Radau"
        )
    min_points = _BEAM_INTEGRATION_MIN_POINTS[integration]
    if num_int_pts < min_points:
        raise ValueError(
            f"{elem_type} {integration} integration requires num_int_pts >= {min_points}"
        )


def _normalize_time_series(ts):
    if ts is None:
        return []
    if isinstance(ts, dict):
        return [ts]
    if isinstance(ts, list):
        return ts
    raise ValueError("time_series must be a list or object")


def _format_list(values):
    return " ".join(str(v) for v in values)


def _analysis_numberer(analysis, default="RCM"):
    numberer = analysis.get("numberer", default)
    if numberer not in ("RCM", "Plain"):
        raise ValueError(f"unsupported numberer: {numberer}")
    return numberer


_SUPPORTED_SYSTEM_NAMES = frozenset(
    {
        "BandGeneral",
        "BandSPD",
        "ProfileSPD",
        "SuperLU",
        "UmfPack",
        "FullGeneral",
        "SparseSYM",
    }
)

_SYSTEM_NAME_ALIASES = {
    "BandGEN": "BandGeneral",
    "BandGen": "BandGeneral",
    "SparseGeneral": "SuperLU",
    "SparseGEN": "SuperLU",
    "SparseSPD": "SparseSYM",
    "Umfpack": "UmfPack",
}


def _canonicalize_system_name(system):
    if not isinstance(system, str) or not system:
        raise ValueError("analysis system must be a non-empty string")
    canonical = _SYSTEM_NAME_ALIASES.get(system, system)
    if canonical == "Mumps" or canonical not in _SUPPORTED_SYSTEM_NAMES:
        supported = ", ".join(sorted(_SUPPORTED_SYSTEM_NAMES))
        raise ValueError(
            f"unsupported analysis system `{system}` (supported: {supported})"
        )
    return canonical


def _analysis_system_line(analysis, default="BandGeneral", default_options=None):
    system = _canonicalize_system_name(analysis.get("system", default))
    options = analysis.get("system_options", default_options or [])
    if not isinstance(options, list) or not all(isinstance(opt, str) for opt in options):
        raise ValueError("analysis system_options must be a list of strings")
    words = ["system", system, *options]
    return " ".join(words)


def _load_control_integrator_line(integrator, default_step):
    step = float(integrator.get("step", default_step))
    words = ["integrator", "LoadControl", str(step)]
    if any(
        key in integrator for key in ("num_iter", "min_step", "max_step")
    ):
        num_iter = int(integrator.get("num_iter", 1))
        words.append(str(num_iter))
        if "min_step" in integrator or "max_step" in integrator:
            min_step = integrator.get("min_step", step)
            words.append(str(float(min_step)))
            if "max_step" in integrator:
                words.append(str(float(integrator["max_step"])))
    return " ".join(words)


def _displacement_control_integrator_line(integrator, node, dof, du_token):
    words = [
        "integrator",
        "DisplacementControl",
        str(int(node)),
        str(int(dof)),
        du_token,
    ]
    if any(key in integrator for key in ("num_iter", "min_du", "max_du")):
        words.append(str(int(integrator.get("num_iter", 1))))
        if "min_du" in integrator or "max_du" in integrator:
            min_du = integrator.get("min_du", du_token)
            words.append(str(min_du))
            if "max_du" in integrator:
                words.append(str(float(integrator["max_du"])))
    return " ".join(words)


def _emit_print_commands(f, command_owner):
    commands = command_owner.get("print_commands", [])
    if not isinstance(commands, list):
        raise ValueError("print_commands must be a list")
    for command in commands:
        if not isinstance(command, dict):
            raise ValueError("print_commands entries must be objects")
        args = command.get("args", [])
        if not isinstance(args, list):
            raise ValueError("print command args must be a list")
        if args:
            f.write("print " + " ".join(str(arg) for arg in args) + "\n")
        else:
            f.write("print\n")


def _resolve_optional_repo_path(path_text, repo_root: Path):
    if not isinstance(path_text, str) or not path_text:
        return None
    path_obj = Path(path_text)
    if path_obj.is_absolute():
        return path_obj
    return (repo_root / path_obj).resolve()


def _iter_relative_path_candidates(base_dir: Path, rel_path: Path, stop_dir: Path | None = None):
    current = base_dir.resolve()
    stop = stop_dir.resolve() if stop_dir is not None else None
    seen = set()
    while True:
        candidate = (current / rel_path).resolve()
        if candidate not in seen:
            seen.add(candidate)
            yield candidate
        if current.parent == current or (stop is not None and current == stop):
            break
        current = current.parent


def _load_path_time_series_values(ts, case_dir: Path, case_data: dict):
    values_path = ts.get("values_path", ts.get("path"))
    if values_path is None:
        raise ValueError("Path time_series missing values_path")

    src = Path(values_path)
    candidates = []
    if src.is_absolute():
        candidates.append(src)
    else:
        repo_root = Path(__file__).resolve().parents[1]
        candidates.extend(_iter_relative_path_candidates(case_dir, src, repo_root))
        candidates.append((repo_root / src).resolve())

        source_example = _resolve_optional_repo_path(case_data.get("source_example"), repo_root)
        if source_example is not None:
            candidates.extend(
                _iter_relative_path_candidates(source_example.parent, src, repo_root)
            )

        source_doc = _resolve_optional_repo_path(case_data.get("source_doc"), repo_root)
        if source_doc is not None:
            candidates.extend(
                _iter_relative_path_candidates(source_doc.parent, src, repo_root)
            )

        migration = case_data.get("migration", {})
        ground_motion = migration.get("ground_motion", {}) if isinstance(migration, dict) else {}
        source_file = _resolve_optional_repo_path(ground_motion.get("source_file"), repo_root)
        if source_file is not None:
            candidates.extend(
                _iter_relative_path_candidates(source_file.parent, src, repo_root)
            )

        # Keep backward compatibility with callers that rely on current working directory.
        candidates.append(Path(values_path))

    src = next((p for p in candidates if p.exists()), None)
    if src is None:
        checked = ", ".join(str(p) for p in candidates)
        raise ValueError(
            f"Path time_series values_path not found: {values_path}; checked: {checked}"
        )
    text = src.read_text(encoding="utf-8")
    tokens = re.findall(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eEdD][-+]?\d+)?", text)
    if not tokens:
        raise ValueError(f"Path time_series values_path had no numeric values: {src}")
    return [float(tok.replace("D", "E").replace("d", "e")) for tok in tokens]


def _emit_time_series(f, ts, case_dir: Path, case_data: dict):
    ts_type = ts.get("type")
    tag = ts.get("tag")
    if ts_type is None or tag is None:
        raise ValueError("time_series requires type and tag")
    factor = ts.get("factor", 1.0)

    if ts_type == "Constant":
        f.write(f"timeSeries Constant {tag} -factor {factor}\n")
    elif ts_type == "Linear":
        f.write(f"timeSeries Linear {tag} -factor {factor}\n")
    elif ts_type in ("Path", "PathFile"):
        if "dt" in ts and "time" in ts:
            raise ValueError("Path time_series cannot specify both dt and time")
        if "values" in ts and ("values_path" in ts or "path" in ts):
            raise ValueError("Path time_series cannot specify both values and values_path/path")
        values = ts.get("values")
        if values is None:
            values = _load_path_time_series_values(ts, case_dir, case_data)
        line = f"timeSeries Path {tag} "
        if "dt" in ts:
            line += f"-dt {ts['dt']} "
        elif "time" in ts:
            line += f"-time {{{_format_list(ts['time'])}}} "
        else:
            raise ValueError("Path time_series requires dt or time")
        line += f"-values {{{_format_list(values)}}} -factor {factor}"
        if ts.get("use_last", False):
            line += " -useLast"
        f.write(line + "\n")
    elif ts_type == "Trig":
        for key in ("t_start", "t_finish", "period"):
            if key not in ts:
                raise ValueError(f"Trig time_series missing {key}")
        line = (
            f"timeSeries Trig {tag} {ts['t_start']} {ts['t_finish']} {ts['period']}"
            f" -phaseShift {ts.get('phase_shift', 0.0)}"
            f" -factor {factor}"
            f" -zeroShift {ts.get('zero_shift', 0.0)}"
        )
        f.write(line + "\n")
    else:
        raise ValueError(f"unsupported time_series type: {ts_type}")


def _normalize_dampings(dampings):
    if dampings is None:
        return []
    if isinstance(dampings, dict):
        return [dampings]
    if isinstance(dampings, list):
        return dampings
    raise ValueError("dampings must be a list or object")


def _emit_damping(f, damping):
    damping_type = damping.get("type")
    damping_tag = damping.get("id", damping.get("tag"))
    if damping_type is None or damping_tag is None:
        raise ValueError("damping requires type and id/tag")
    if damping_type not in ("SecStif", "SecStiff"):
        raise ValueError(f"unsupported damping type: {damping_type}")
    if "beta" not in damping:
        raise ValueError("SecStif damping requires beta")
    line = f"damping SecStif {damping_tag} {damping['beta']}"
    if "activateTime" in damping:
        line += f" -activateTime {damping['activateTime']}"
    if "deactivateTime" in damping:
        line += f" -deactivateTime {damping['deactivateTime']}"
    if "factor" in damping:
        line += f" -factor {damping['factor']}"
    f.write(line + "\n")


def _emit_element_load(f, elem_load, ndm):
    elem_id = _require_field(elem_load, "element")
    load_type = _require_field(elem_load, "type")

    if load_type == "beamUniform":
        if ndm == 2:
            wy = float(elem_load.get("wy", elem_load.get("w", 0.0)))
            if "wx" in elem_load:
                wx = float(elem_load["wx"])
                f.write(f"  eleLoad -ele {elem_id} -type -beamUniform {wy} {wx}\n")
            else:
                f.write(f"  eleLoad -ele {elem_id} -type -beamUniform {wy}\n")
            return
        if ndm == 3:
            if "wy" not in elem_load or "wz" not in elem_load:
                raise ValueError("3D beamUniform requires wy and wz")
            wy = float(elem_load["wy"])
            wz = float(elem_load["wz"])
            if "wx" in elem_load:
                wx = float(elem_load["wx"])
                f.write(f"  eleLoad -ele {elem_id} -type -beamUniform {wy} {wz} {wx}\n")
            else:
                f.write(f"  eleLoad -ele {elem_id} -type -beamUniform {wy} {wz}\n")
            return
        raise ValueError("beamUniform only supports ndm=2 or ndm=3")

    if load_type == "beamPoint":
        x = float(_require_field(elem_load, "x"))
        if x < 0.0 or x > 1.0:
            raise ValueError("beamPoint x must be in [0, 1]")
        if ndm == 2:
            if "py" not in elem_load:
                raise ValueError("2D beamPoint requires py")
            py = float(elem_load["py"])
            if "px" in elem_load:
                px = float(elem_load["px"])
                f.write(f"  eleLoad -ele {elem_id} -type -beamPoint {py} {x} {px}\n")
            else:
                f.write(f"  eleLoad -ele {elem_id} -type -beamPoint {py} {x}\n")
            return
        if ndm == 3:
            if "py" not in elem_load or "pz" not in elem_load:
                raise ValueError("3D beamPoint requires py and pz")
            py = float(elem_load["py"])
            pz = float(elem_load["pz"])
            if "px" in elem_load:
                px = float(elem_load["px"])
                f.write(f"  eleLoad -ele {elem_id} -type -beamPoint {py} {pz} {x} {px}\n")
            else:
                f.write(f"  eleLoad -ele {elem_id} -type -beamPoint {py} {pz} {x}\n")
            return
        raise ValueError("beamPoint only supports ndm=2 or ndm=3")

    raise ValueError(f"unsupported element load type: {load_type}")


def _algorithm_cmd(algorithm_name, cfg):
    algorithm_options = {}
    algorithm_options = cfg.get("algorithm_options", {})
    if algorithm_options is None:
        algorithm_options = {}
    if not isinstance(algorithm_options, dict):
        raise ValueError("algorithm_options must be an object")
    if algorithm_name == "ModifiedNewtonInitial":
        return "ModifiedNewton -initial"
    if algorithm_name == "Broyden":
        count = int(cfg.get("broyden_count", algorithm_options.get("max_iters", 8)))
        return f"Broyden {count}"
    if algorithm_name == "NewtonLineSearch":
        eta = float(cfg.get("line_search_eta", algorithm_options.get("alpha", 0.8)))
        return f"NewtonLineSearch {eta}"
    return algorithm_name


_NONLINEAR_ALGORITHMS = (
    "Newton",
    "ModifiedNewton",
    "ModifiedNewtonInitial",
    "Broyden",
    "NewtonLineSearch",
)


def _validate_nonlinear_algorithm(algorithm_name, label):
    if algorithm_name not in _NONLINEAR_ALGORITHMS:
        raise ValueError(f"unsupported {label} algorithm: {algorithm_name}")


def _validate_static_nonlinear_algorithm(algorithm_name, label):
    _validate_nonlinear_algorithm(algorithm_name, label)


def _validate_static_nonlinear_test_type(test_type, label):
    if test_type not in ("NormDispIncr", "NormUnbalance", "EnergyIncr"):
        raise ValueError(
            f"{label} test_type must be NormDispIncr, NormUnbalance, or EnergyIncr"
        )


def _validate_transient_nonlinear_test_type(test_type, label):
    if test_type not in ("NormUnbalance", "NormDispIncr", "EnergyIncr"):
        raise ValueError(
            f"{label} test_type must be NormUnbalance, NormDispIncr, or EnergyIncr"
        )


def _validate_displacement_control_cutback(integrator, label):
    cutback = float(integrator.get("cutback", 0.5))
    max_cutbacks = int(integrator.get("max_cutbacks", 8))
    min_du = float(integrator.get("min_du", 1.0e-10))
    if not (0.0 < cutback < 1.0):
        raise ValueError(f"{label} cutback must be in (0, 1)")
    if max_cutbacks < 0:
        raise ValueError(f"{label} max_cutbacks must be >= 0")
    if min_du <= 0.0:
        raise ValueError(f"{label} min_du must be > 0")
    return cutback, max_cutbacks, min_du


def _tcl_static_nonlinear_test_type(test_type):
    return test_type


def _test_command_line(test_type, tol, max_iters, print_flag=None, extra_args=None):
    words = ["test", str(test_type), str(tol), str(int(max_iters))]
    if print_flag is not None:
        words.append(str(int(print_flag)))
    if extra_args:
        words.extend(str(arg) for arg in extra_args)
    return " ".join(words)


def _normalize_nonlinear_solver_chain(
    analysis,
    *,
    analysis_label,
    default_algorithm,
    default_test_type,
    default_tol,
    default_max_iters,
    validate_test_type,
    tcl_test_type,
):
    base_algorithm = analysis.get("algorithm", default_algorithm)
    base_test_type = analysis.get("test_type", default_test_type)
    base_tol = analysis.get("tol", default_tol)
    base_max_iters = analysis.get("max_iters", default_max_iters)
    if "rel_tol" in analysis:
        raise ValueError(f"{analysis_label} rel_tol is not representable in Tcl/OpenSees")
    base_print_flag = analysis.get("test_print_flag")
    base_extra_args = analysis.get("test_extra_args")
    solver_chain = analysis.get("solver_chain")
    attempts = []

    if solver_chain is not None:
        if not isinstance(solver_chain, list) or len(solver_chain) == 0:
            raise ValueError(f"{analysis_label} solver_chain must be a non-empty list")
        for index, attempt in enumerate(solver_chain):
            if not isinstance(attempt, dict):
                raise ValueError(
                    f"{analysis_label} solver_chain[{index}] must be an object"
                )
            algorithm = attempt.get("algorithm", base_algorithm)
            _validate_nonlinear_algorithm(
                algorithm, f"{analysis_label} solver_chain[{index}]"
            )
            test_type = attempt.get("test_type", base_test_type)
            validate_test_type(test_type, f"{analysis_label} solver_chain[{index}]")
            tol = attempt.get("tol", base_tol)
            max_iters = attempt.get("max_iters", base_max_iters)
            if "rel_tol" in attempt:
                raise ValueError(
                    f"{analysis_label} solver_chain[{index}] rel_tol is not representable in Tcl/OpenSees"
                )
            print_flag = attempt.get("test_print_flag", base_print_flag)
            extra_args = attempt.get("test_extra_args", base_extra_args)
            attempts.append(
                {
                    "algorithm": algorithm,
                    "algorithm_cmd": _algorithm_cmd(algorithm, attempt),
                    "test_type": test_type,
                    "tcl_test_type": tcl_test_type(test_type),
                    "tol": tol,
                    "max_iters": max_iters,
                    "test_print_flag": print_flag,
                    "test_extra_args": extra_args,
                }
            )
        return attempts

    _validate_nonlinear_algorithm(base_algorithm, analysis_label)
    validate_test_type(base_test_type, analysis_label)
    attempts.append(
        {
            "algorithm": base_algorithm,
            "algorithm_cmd": _algorithm_cmd(base_algorithm, analysis),
            "test_type": base_test_type,
            "tcl_test_type": tcl_test_type(base_test_type),
            "tol": base_tol,
            "max_iters": base_max_iters,
            "test_print_flag": base_print_flag,
            "test_extra_args": base_extra_args,
        }
    )
    return attempts


def _append_solver_chain_retry_lines(
    lines,
    ok_var,
    analyze_cmd,
    solver_chain,
    *,
    indent,
    retry_integrator_line=None,
):
    primary_attempt = solver_chain[0]
    if len(solver_chain) == 1:
        return
    for attempt in solver_chain[1:]:
        lines.append(f"{indent}if {{${ok_var} != 0}} {{")
        lines.append(
            f"{indent}  "
            + _test_command_line(
                attempt["tcl_test_type"],
                attempt["tol"],
                attempt["max_iters"],
                attempt.get("test_print_flag"),
                attempt.get("test_extra_args"),
            )
        )
        lines.append(f"{indent}  algorithm {attempt['algorithm_cmd']}")
        if retry_integrator_line is not None:
            lines.append(f"{indent}  {retry_integrator_line}")
        lines.append(f"{indent}  set {ok_var} [{analyze_cmd}]")
        lines.append(f"{indent}}}")
    lines.append(
        f"{indent}"
        + _test_command_line(
            primary_attempt["tcl_test_type"],
            primary_attempt["tol"],
            primary_attempt["max_iters"],
            primary_attempt.get("test_print_flag"),
            primary_attempt.get("test_extra_args"),
        )
    )
    lines.append(f"{indent}algorithm {primary_attempt['algorithm_cmd']}")


def _static_nonlinear_displacement_control_post_lines(
    node,
    dof,
    integrator_line,
    targets,
    cutback,
    max_cutbacks,
    min_du,
    solver_chain,
):
    lines = [
        "set strut_dc_targets {" + " ".join(str(float(val)) for val in targets) + "}",
        f"set strut_dc_cutback {cutback}",
        f"set strut_dc_max_cutbacks {max_cutbacks}",
        f"set strut_dc_min_du {min_du}",
        "foreach strut_dc_targ $strut_dc_targets {",
        "  while {1} {",
        f"    set strut_dc_curr [nodeDisp {int(node)} {int(dof)}]",
        "    set strut_dc_remaining [expr {$strut_dc_targ - $strut_dc_curr}]",
        "    if {[expr abs($strut_dc_remaining)] <= $strut_dc_min_du} {",
        "      break",
        "    }",
        "    set strut_dc_try_du $strut_dc_remaining",
        "    set strut_dc_ok 1",
        "    for {set strut_dc_cut 0} {$strut_dc_cut <= $strut_dc_max_cutbacks} {incr strut_dc_cut} {",
        f"      {integrator_line}",
        "      set strut_dc_ok [analyze 1]",
    ]
    _append_solver_chain_retry_lines(
        lines,
        "strut_dc_ok",
        "analyze 1",
        solver_chain,
        indent="      ",
        retry_integrator_line=integrator_line,
    )
    lines.extend(
        [
            "      if {$strut_dc_ok == 0} {",
            "        break",
            "      }",
            "      set strut_dc_try_du [expr {$strut_dc_try_du * $strut_dc_cutback}]",
            "      if {[expr abs($strut_dc_try_du)] <= $strut_dc_min_du} {",
            "        break",
            "      }",
            "    }",
            "    if {$strut_dc_ok != 0} {",
            "      error \"analysis failed\"",
            "    }",
            "  }",
            "}",
        ]
    )
    return lines


def _emit_recorders(f, recorders, node_by_id, ndf):
    for rec in recorders:
        rec_type = rec["type"]
        if rec_type == "node_displacement":
            dofs = rec["dofs"]
            output = rec.get("output", "node_disp")
            for node_id in rec["nodes"]:
                filename = f"{output}_node{node_id}.out"
                f.write(
                    f"recorder Node -file {filename} -node {node_id} -dof {' '.join(str(d) for d in dofs)} disp\n"
                )
        elif rec_type == "element_force":
            output = rec.get("output", "element_force")
            for elem_id in rec["elements"]:
                filename = f"{output}_ele{elem_id}.out"
                f.write(f"recorder Element -file {filename} -ele {elem_id} force\n")
        elif rec_type == "element_local_force":
            output = rec.get("output", "element_local_force")
            for elem_id in rec["elements"]:
                filename = f"{output}_ele{elem_id}.out"
                f.write(f"recorder Element -file {filename} -ele {elem_id} localForce\n")
        elif rec_type == "element_basic_force":
            output = rec.get("output", "element_basic_force")
            for elem_id in rec["elements"]:
                filename = f"{output}_ele{elem_id}.out"
                f.write(f"recorder Element -file {filename} -ele {elem_id} basicForce\n")
        elif rec_type == "element_deformation":
            output = rec.get("output", "element_deformation")
            for elem_id in rec["elements"]:
                filename = f"{output}_ele{elem_id}.out"
                f.write(f"recorder Element -file {filename} -ele {elem_id} deformation\n")
        elif rec_type == "node_reaction":
            dofs = rec["dofs"]
            output = rec.get("output", "reaction")
            for node_id in rec["nodes"]:
                filename = f"{output}_node{node_id}.out"
                f.write(
                    f"recorder Node -file {filename} -node {node_id} -dof {' '.join(str(d) for d in dofs)} reaction\n"
                )
        elif rec_type == "drift":
            i_node = rec["i_node"]
            j_node = rec["j_node"]
            dof = rec["dof"]
            perp_dirn = rec["perp_dirn"]
            output = rec.get("output", "drift")
            filename = f"{output}_i{i_node}_j{j_node}.out"
            f.write(
                f"recorder Drift -file {filename} -iNode {i_node} -jNode {j_node} -dof {dof} -perpDirn {perp_dirn}\n"
            )
        elif rec_type == "envelope_element_force":
            output = rec.get("output", "envelope_element_force")
            for elem_id in rec["elements"]:
                filename = f"{output}_ele{elem_id}.out"
                time_flag = "-time " if rec.get("include_time") else ""
                f.write(
                    f"recorder EnvelopeElement {time_flag}-file {filename} -ele {elem_id} forces\n"
                )
        elif rec_type == "envelope_element_local_force":
            output = rec.get("output", "envelope_element_local_force")
            for elem_id in rec["elements"]:
                filename = f"{output}_ele{elem_id}.out"
                time_flag = "-time " if rec.get("include_time") else ""
                f.write(
                    f"recorder EnvelopeElement {time_flag}-file {filename} -ele {elem_id} localForce\n"
                )
        elif rec_type == "envelope_node_displacement":
            dofs = rec["dofs"]
            output = rec.get("output", "envelope_node_displacement")
            for node_id in rec["nodes"]:
                filename = f"{output}_node{node_id}.out"
                time_flag = "-time " if rec.get("include_time") else ""
                f.write(
                    f"recorder EnvelopeNode {time_flag}-file {filename} -node {node_id} -dof {' '.join(str(d) for d in dofs)} disp\n"
                )
        elif rec_type == "envelope_node_acceleration":
            dofs = rec["dofs"]
            output = rec.get("output", "envelope_node_acceleration")
            time_series_flag = ""
            if "time_series" in rec:
                time_series_flag = f"-timeSeries {int(rec['time_series'])} "
            for node_id in rec["nodes"]:
                filename = f"{output}_node{node_id}.out"
                time_flag = "-time " if rec.get("include_time") else ""
                f.write(
                    f"recorder EnvelopeNode {time_flag}-file {filename} {time_series_flag}-node {node_id} -dof {' '.join(str(d) for d in dofs)} accel\n"
                )
        elif rec_type == "section_force" or rec_type == "section_deformation":
            output = rec.get("output", rec_type)
            response = "force" if rec_type == "section_force" else "deformation"
            sections = rec.get("sections")
            if sections is None:
                if "section" not in rec:
                    raise ValueError(f"{rec_type} recorder requires section or sections")
                sections = [rec["section"]]
            if not isinstance(sections, list) or len(sections) == 0:
                raise ValueError(f"{rec_type} recorder requires non-empty sections")
            for elem_id in rec["elements"]:
                for sec_no in sections:
                    sec_idx = int(sec_no)
                    filename = f"{output}_ele{elem_id}_sec{sec_idx}.out"
                    f.write(
                        f"recorder Element -file {filename} -ele {elem_id} section {sec_idx} {response}\n"
                    )
        elif rec_type == "modal_eigen":
            # Modal outputs are emitted explicitly after `eigen`, not through recorder commands.
            pass
        else:
            raise ValueError(f"unsupported recorder type: {rec_type}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("json_file")
    parser.add_argument("tcl_out")
    args = parser.parse_args()

    json_path = Path(args.json_file)
    data = json.loads(json_path.read_text())
    case_dir = json_path.parent
    schema_version = data.get("schema_version", "1.0")
    if schema_version != "1.0":
        raise ValueError(f"unsupported schema_version: {schema_version}")

    model = _require_field(data, "model")
    ndm = _require_field(model, "ndm")
    ndf = _require_field(model, "ndf")

    nodes = _require_field(data, "nodes")
    elements = _require_field(data, "elements")
    sections = {sec["id"]: sec for sec in data.get("sections", [])}
    materials = {mat["id"]: mat for mat in data.get("materials", [])}
    node_by_id = {node["id"]: node for node in nodes}

    recorders = data.get("recorders", [])

    tcl_path = Path(args.tcl_out)
    tcl_path.parent.mkdir(parents=True, exist_ok=True)

    with tcl_path.open("w", encoding="utf-8") as f:
        _write_header(f)
        f.write(f"model BasicBuilder -ndm {ndm} -ndf {ndf}\n")

        for node in nodes:
            node_id = node["id"]
            if ndm == 2:
                f.write(f"node {node_id} {node['x']} {node['y']}\n")
            elif ndm == 3:
                if "z" not in node:
                    raise ValueError(f"ndm=3 node {node_id} missing z coordinate")
                f.write(f"node {node_id} {node['x']} {node['y']} {node['z']}\n")
            else:
                raise ValueError("ndm must be 2 or 3")

            fix = _constraints_to_fix(ndf, node.get("constraints"))
            if fix is not None:
                f.write(f"fix {node_id} {' '.join(str(v) for v in fix)}\n")

        mp_constraints = data.get("mp_constraints", [])
        for mpc in mp_constraints:
            mpc_type = mpc.get("type")
            if mpc_type != "equalDOF":
                raise ValueError(f"unsupported mp constraint type: {mpc_type}")
            retained = mpc.get("retained_node")
            constrained_node = mpc.get("constrained_node")
            dofs = mpc.get("dofs", [])
            if retained not in node_by_id:
                raise ValueError(f"equalDOF retained_node {retained} not found")
            if constrained_node not in node_by_id:
                raise ValueError(f"equalDOF constrained_node {constrained_node} not found")
            if not isinstance(dofs, list) or not dofs:
                raise ValueError("equalDOF requires non-empty dofs list")
            dof_vals = []
            for dof in dofs:
                if not isinstance(dof, int) or dof < 1 or dof > ndf:
                    raise ValueError(f"equalDOF dof {dof} out of range 1..{ndf}")
                dof_vals.append(str(dof))
            f.write(f"equalDOF {retained} {constrained_node} {' '.join(dof_vals)}\n")

        # Nodal masses (lumped)
        masses = data.get("masses", [])
        if masses:
            mass_map = {}
            for entry in masses:
                node_id = entry["node"]
                dof = entry["dof"]
                value = entry["value"]
                if dof < 1 or dof > ndf:
                    raise ValueError(f"mass dof {dof} out of range 1..{ndf}")
                vec = mass_map.setdefault(node_id, [0.0] * ndf)
                vec[dof - 1] += value
            for node_id, vec in mass_map.items():
                if node_id not in node_by_id:
                    raise ValueError(f"mass node {node_id} not found")
                f.write(f"mass {node_id} {' '.join(str(v) for v in vec)}\n")

        # Materials (Elastic/Steel01/Steel02/Concrete01/Concrete02 uniaxial or ElasticIsotropic)
        for mat in materials.values():
            params = mat["params"]
            if mat["type"] == "Elastic":
                E = params["E"]
                f.write(f"uniaxialMaterial Elastic {mat['id']} {E}\n")
            elif mat["type"] == "Steel01":
                fy = params["Fy"]
                E0 = params["E0"]
                b = params["b"]
                f.write(f"uniaxialMaterial Steel01 {mat['id']} {fy} {E0} {b}\n")
            elif mat["type"] == "Steel02":
                fy = params["Fy"]
                E0 = params["E0"]
                b = params["b"]
                has_r = all(k in params for k in ("R0", "cR1", "cR2"))
                has_r_any = any(k in params for k in ("R0", "cR1", "cR2"))
                has_a = all(k in params for k in ("a1", "a2", "a3", "a4"))
                has_a_any = any(k in params for k in ("a1", "a2", "a3", "a4"))
                has_siginit = "sigInit" in params
                if has_r_any and not has_r:
                    raise ValueError("Steel02 requires R0, cR1, cR2 together")
                if has_a_any and not has_a:
                    raise ValueError("Steel02 requires a1, a2, a3, a4 together")
                if has_a and not has_r:
                    raise ValueError("Steel02 a1-a4 require R0/cR1/cR2")
                if has_siginit and not has_a:
                    raise ValueError("Steel02 sigInit requires a1-a4 and R0/cR1/cR2")
                if has_siginit:
                    f.write(
                        "uniaxialMaterial Steel02 "
                        f"{mat['id']} {fy} {E0} {b} "
                        f"{params['R0']} {params['cR1']} {params['cR2']} "
                        f"{params['a1']} {params['a2']} {params['a3']} {params['a4']} "
                        f"{params['sigInit']}\n"
                    )
                elif has_a:
                    f.write(
                        "uniaxialMaterial Steel02 "
                        f"{mat['id']} {fy} {E0} {b} "
                        f"{params['R0']} {params['cR1']} {params['cR2']} "
                        f"{params['a1']} {params['a2']} {params['a3']} {params['a4']}\n"
                    )
                elif has_r:
                    f.write(
                        "uniaxialMaterial Steel02 "
                        f"{mat['id']} {fy} {E0} {b} "
                        f"{params['R0']} {params['cR1']} {params['cR2']}\n"
                    )
                else:
                    f.write(f"uniaxialMaterial Steel02 {mat['id']} {fy} {E0} {b}\n")
            elif mat["type"] == "Concrete01":
                fpc = params["fpc"]
                epsc0 = params["epsc0"]
                fpcu = params["fpcu"]
                epscu = params["epscu"]
                f.write(
                    f"uniaxialMaterial Concrete01 {mat['id']} {fpc} {epsc0} {fpcu} {epscu}\n"
                )
            elif mat["type"] == "Concrete02":
                fpc = params["fpc"]
                epsc0 = params["epsc0"]
                fpcu = params["fpcu"]
                epscu = params["epscu"]
                has_rat = "rat" in params
                has_ft = "ft" in params
                has_ets = "Ets" in params
                if has_rat != has_ft or has_rat != has_ets:
                    raise ValueError("Concrete02 requires rat, ft, Ets together")
                if has_rat:
                    f.write(
                        "uniaxialMaterial Concrete02 "
                        f"{mat['id']} {fpc} {epsc0} {fpcu} {epscu} "
                        f"{params['rat']} {params['ft']} {params['Ets']}\n"
                    )
                else:
                    f.write(
                        f"uniaxialMaterial Concrete02 {mat['id']} {fpc} {epsc0} {fpcu} {epscu}\n"
                    )
            elif mat["type"] == "ElasticIsotropic":
                E = params["E"]
                nu = params["nu"]
                rho = params.get("rho", 0.0)
                f.write(f"nDMaterial ElasticIsotropic {mat['id']} {E} {nu} {rho}\n")
            else:
                raise ValueError(f"unsupported material type: {mat['type']}")

        # Sections (elastic, membrane/plate, or FiberSection2d/FiberSection3d subset)
        for sec in sections.values():
            params = sec["params"]
            if sec["type"] == "ElasticSection2d":
                E = params["E"]
                A = params["A"]
                I = params["I"]
                f.write(f"section Elastic {sec['id']} {E} {A} {I}\n")
            elif sec["type"] == "ElasticSection3d":
                E = params["E"]
                A = params["A"]
                Iz = params["Iz"]
                Iy = params["Iy"]
                G = params["G"]
                J = params["J"]
                f.write(f"section Elastic {sec['id']} {E} {A} {Iz} {Iy} {G} {J}\n")
            elif sec["type"] == "ElasticMembranePlateSection":
                E = params["E"]
                nu = params["nu"]
                h = params["h"]
                rho = params.get("rho", 0.0)
                f.write(
                    f"section ElasticMembranePlateSection {sec['id']} {E} {nu} {h} {rho}\n"
                )
            elif sec["type"] == "AggregatorSection2d":
                response_order = (
                    ("axial_material", "P"),
                    ("flexural_material", "Mz"),
                    ("moment_y_material", "My"),
                    ("torsion_material", "T"),
                    ("shear_y_material", "Vy"),
                    ("shear_z_material", "Vz"),
                )
                tokens = []
                for material_key, response_name in response_order:
                    material_id = int(params.get(material_key, -1))
                    if material_id < 0:
                        continue
                    if material_id not in materials:
                        raise ValueError(
                            f"AggregatorSection2d material {material_id} not found"
                        )
                    if materials[material_id]["type"] == "ElasticIsotropic":
                        raise ValueError(
                            "AggregatorSection2d requires uniaxial materials"
                        )
                    tokens.extend((str(material_id), response_name))
                base_section = int(params.get("base_section", -1))
                if base_section >= 0:
                    tokens.extend(("-section", str(base_section)))
                if not tokens:
                    raise ValueError(
                        "AggregatorSection2d requires at least one uniaxial response"
                    )
                f.write(f"section Aggregator {sec['id']} {' '.join(tokens)}\n")
            elif sec["type"] in ("FiberSection2d", "FiberSection3d"):
                sec_type = sec["type"]
                patches = params.get("patches", [])
                layers = params.get("layers", [])
                if not patches and not layers:
                    raise ValueError(f"{sec_type} requires at least one patch or layer")
                if sec_type == "FiberSection3d":
                    G = params.get("G", 0.0)
                    J = params.get("J", 0.0)
                    if G <= 0.0 or J <= 0.0:
                        raise ValueError("FiberSection3d requires positive G and J")
                    f.write(f"section Fiber {sec['id']} -GJ {G * J} {{\n")
                else:
                    f.write(f"section Fiber {sec['id']} {{\n")
                for patch in patches:
                    patch_type = patch.get("type")
                    if patch_type == "quad":
                        patch_type = "quadr"
                    mat = patch["material"]
                    if mat not in materials:
                        raise ValueError(f"{sec_type} patch material {mat} not found")
                    if materials[mat]["type"] == "ElasticIsotropic":
                        raise ValueError(
                            f"{sec_type} patch requires uniaxial material (not ElasticIsotropic)"
                        )
                    ny = patch["num_subdiv_y"]
                    nz = patch["num_subdiv_z"]
                    if ny <= 0 or nz <= 0:
                        raise ValueError(
                            f"{sec_type} patch requires num_subdiv_y and num_subdiv_z > 0"
                        )
                    if patch_type == "rect":
                        yi = patch["y_i"]
                        zi = patch["z_i"]
                        yj = patch["y_j"]
                        zj = patch["z_j"]
                        f.write(
                            f"  patch rect {mat} {ny} {nz} {yi} {zi} {yj} {zj}\n"
                        )
                    elif patch_type == "quadr":
                        yi = patch["y_i"]
                        zi = patch["z_i"]
                        yj = patch["y_j"]
                        zj = patch["z_j"]
                        yk = patch["y_k"]
                        zk = patch["z_k"]
                        yl = patch["y_l"]
                        zl = patch["z_l"]
                        f.write(
                            "  patch quadr "
                            f"{mat} {ny} {nz} "
                            f"{yi} {zi} {yj} {zj} {yk} {zk} {yl} {zl}\n"
                        )
                    else:
                        raise ValueError(
                            f"unsupported {sec_type} patch type: {patch_type}"
                        )
                for layer in layers:
                    layer_type = layer.get("type")
                    if layer_type != "straight":
                        raise ValueError(
                            f"unsupported {sec_type} layer type: {layer_type}"
                        )
                    mat = layer["material"]
                    if mat not in materials:
                        raise ValueError(f"{sec_type} layer material {mat} not found")
                    if materials[mat]["type"] == "ElasticIsotropic":
                        raise ValueError(
                            f"{sec_type} layer requires uniaxial material (not ElasticIsotropic)"
                        )
                    num_bars = layer["num_bars"]
                    bar_area = layer["bar_area"]
                    y_start = layer["y_start"]
                    z_start = layer["z_start"]
                    y_end = layer["y_end"]
                    z_end = layer["z_end"]
                    if num_bars <= 0:
                        raise ValueError(
                            f"{sec_type} layer straight requires num_bars > 0"
                        )
                    if bar_area <= 0:
                        raise ValueError(
                            f"{sec_type} layer straight requires bar_area > 0"
                        )
                    f.write(
                        "  layer straight "
                        f"{mat} {num_bars} {bar_area} "
                        f"{y_start} {z_start} {y_end} {z_end}\n"
                    )
                f.write("}\n")
            else:
                raise ValueError(f"unsupported section type: {sec['type']}")

        # Geometric transformations (only for beam-column elements)
        transf_tags = {}
        next_tag = 1
        for elem in elements:
            if elem["type"] not in (
                "elasticBeamColumn2d",
                "elasticBeamColumn3d",
                "forceBeamColumn2d",
                "dispBeamColumn2d",
                "forceBeamColumn3d",
                "dispBeamColumn3d",
            ):
                continue
            name = elem.get("geomTransf", "Linear")
            if elem["type"] in (
                "elasticBeamColumn3d",
                "forceBeamColumn3d",
                "dispBeamColumn3d",
            ):
                n1_id, n2_id = elem["nodes"]
                vecxz = _choose_vecxz(node_by_id[n1_id], node_by_id[n2_id])
                key = (name, vecxz)
            else:
                key = (name, None)
            if key not in transf_tags:
                transf_tags[key] = next_tag
                if key[1] is None:
                    f.write(f"geomTransf {name} {next_tag}\n")
                else:
                    vx, vy, vz = key[1]
                    f.write(f"geomTransf {name} {next_tag} {vx} {vy} {vz}\n")
                next_tag += 1

        # Beam integrations (force/disp beam-column)
        integration_tags = {}
        next_int_tag = 1
        for elem in elements:
            elem_type = elem["type"]
            if elem_type not in (
                "forceBeamColumn2d",
                "dispBeamColumn2d",
                "forceBeamColumn3d",
                "dispBeamColumn3d",
            ):
                continue
            sec = sections[elem["section"]]
            is_3d = elem_type in ("forceBeamColumn3d", "dispBeamColumn3d")
            if is_3d:
                if sec["type"] not in ("ElasticSection3d", "FiberSection3d"):
                    raise ValueError(f"{elem_type} requires ElasticSection3d or FiberSection3d")
                if sec["type"] == "FiberSection3d":
                    if sec["params"].get("G", 0.0) <= 0.0 or sec["params"].get("J", 0.0) <= 0.0:
                        raise ValueError(
                            f"{elem_type} with FiberSection3d requires positive G and J"
                        )
            elif sec["type"] not in (
                "FiberSection2d",
                "ElasticSection2d",
                "AggregatorSection2d",
            ):
                raise ValueError(
                    f"{elem_type} requires FiberSection2d, ElasticSection2d, or AggregatorSection2d"
                )
            geom = elem.get("geomTransf", "Linear")
            if is_3d:
                if geom not in ("Linear", "PDelta", "Corotational"):
                    raise ValueError(
                        f"{elem_type} supports geomTransf Linear, PDelta, or Corotational"
                    )
            elif geom not in ("Linear", "PDelta", "Corotational"):
                raise ValueError(
                    f"{elem_type} supports geomTransf Linear, PDelta, or Corotational"
                )
            integration = elem.get("integration", "Lobatto")
            num_int_pts = int(elem.get("num_int_pts", 3))
            _validate_beam_integration(elem_type, integration, num_int_pts)
            key = (integration, elem["section"], num_int_pts)
            if key in integration_tags:
                continue
            integration_tags[key] = next_int_tag
            f.write(
                f"beamIntegration {integration} {next_int_tag} {elem['section']} {num_int_pts}\n"
            )
            next_int_tag += 1

        ts_tags = set()
        ts_list = _normalize_time_series(data.get("time_series"))
        for ts in ts_list:
            _emit_time_series(f, ts, case_dir, data)
        ts_tags = {ts["tag"] for ts in ts_list}

        for damping in _normalize_dampings(data.get("dampings")):
            _emit_damping(f, damping)

        # Elements (elasticBeamColumn2d, truss, zeroLength, zeroLengthSection, twoNodeLink, fourNodeQuad/bbarQuad, shell)
        for elem in elements:
            if elem["type"] == "elasticBeamColumn2d":
                sec = sections[elem["section"]]
                if sec["type"] == "FiberSection2d":
                    raise ValueError(
                        "elasticBeamColumn2d with FiberSection2d requires "
                        "forceBeamColumn2d or dispBeamColumn2d"
                    )
                if sec["type"] != "ElasticSection2d":
                    raise ValueError("elasticBeamColumn2d requires ElasticSection2d")
                params = sec["params"]
                A = params["A"]
                E = params["E"]
                I = params["I"]
                n1, n2 = elem["nodes"]
                transf_tag = transf_tags[(elem.get("geomTransf", "Linear"), None)]
                f.write(
                    f"element elasticBeamColumn {elem['id']} {n1} {n2} {A} {E} {I} {transf_tag}\n"
                )
            elif elem["type"] in (
                "forceBeamColumn2d",
                "dispBeamColumn2d",
                "forceBeamColumn3d",
                "dispBeamColumn3d",
            ):
                elem_type = elem["type"]
                sec = sections[elem["section"]]
                is_3d = elem_type in ("forceBeamColumn3d", "dispBeamColumn3d")
                if is_3d:
                    if sec["type"] not in ("ElasticSection3d", "FiberSection3d"):
                        raise ValueError(f"{elem_type} requires ElasticSection3d or FiberSection3d")
                    if sec["type"] == "FiberSection3d":
                        if sec["params"].get("G", 0.0) <= 0.0 or sec["params"].get("J", 0.0) <= 0.0:
                            raise ValueError(
                                f"{elem_type} with FiberSection3d requires positive G and J"
                            )
                elif sec["type"] not in (
                    "FiberSection2d",
                    "ElasticSection2d",
                    "AggregatorSection2d",
                ):
                    raise ValueError(
                        f"{elem_type} requires FiberSection2d, ElasticSection2d, or AggregatorSection2d"
                    )
                integration = elem.get("integration", "Lobatto")
                num_int_pts = int(elem.get("num_int_pts", 3))
                key = (integration, elem["section"], num_int_pts)
                if key not in integration_tags:
                    raise ValueError(f"{elem_type} integration definition missing")
                n1, n2 = elem["nodes"]
                if is_3d:
                    vecxz = _choose_vecxz(node_by_id[n1], node_by_id[n2])
                    transf_tag = transf_tags[(elem.get("geomTransf", "Linear"), vecxz)]
                else:
                    transf_tag = transf_tags[(elem.get("geomTransf", "Linear"), None)]
                int_tag = integration_tags[key]
                element_cmd = "forceBeamColumn"
                if elem_type in ("dispBeamColumn2d", "dispBeamColumn3d"):
                    element_cmd = "dispBeamColumn"
                f.write(
                    f"element {element_cmd} {elem['id']} {n1} {n2} {transf_tag} {int_tag}\n"
                )
            elif elem["type"] == "elasticBeamColumn3d":
                sec = sections[elem["section"]]
                if sec["type"] != "ElasticSection3d":
                    raise ValueError("elasticBeamColumn3d requires ElasticSection3d")
                params = sec["params"]
                A = params["A"]
                E = params["E"]
                G = params["G"]
                J = params["J"]
                Iy = params["Iy"]
                Iz = params["Iz"]
                n1, n2 = elem["nodes"]
                vecxz = _choose_vecxz(node_by_id[n1], node_by_id[n2])
                transf_tag = transf_tags[(elem.get("geomTransf", "Linear"), vecxz)]
                f.write(
                    f"element elasticBeamColumn {elem['id']} {n1} {n2} {A} {E} {G} {J} {Iy} {Iz} {transf_tag}\n"
                )
            elif elem["type"] == "truss":
                n1, n2 = elem["nodes"]
                area = elem["area"]
                mat_id = elem["material"]
                f.write(f"element truss {elem['id']} {n1} {n2} {area} {mat_id}\n")
            elif elem["type"] == "zeroLength":
                n1, n2 = elem["nodes"]
                mats = " ".join(str(mid) for mid in elem["materials"])
                dirs = " ".join(str(d) for d in elem["dirs"])
                line = f"element zeroLength {elem['id']} {n1} {n2} -mat {mats} -dir {dirs}"
                line += _format_link_orient(elem, ndm)
                damp_mats = elem.get("dampMats")
                if damp_mats:
                    line += f" -dampMats {_format_list(damp_mats)}"
                if "damp" in elem:
                    line += f" -damp {elem['damp']}"
                if elem.get("doRayleigh", False):
                    line += " -doRayleigh 1"
                f.write(line + "\n")
            elif elem["type"] == "zeroLengthSection":
                n1, n2 = elem["nodes"]
                sec_id = elem["section"]
                if sec_id not in sections:
                    raise ValueError("zeroLengthSection section not found")
                sec_type = sections[sec_id]["type"]
                if sec_type not in ("FiberSection2d", "ElasticSection2d"):
                    raise ValueError(
                        "zeroLengthSection requires FiberSection2d or ElasticSection2d"
                    )
                f.write(f"element zeroLengthSection {elem['id']} {n1} {n2} {sec_id}\n")
            elif elem["type"] == "twoNodeLink":
                n1, n2 = elem["nodes"]
                mats = " ".join(str(mid) for mid in elem["materials"])
                dirs = " ".join(str(d) for d in elem["dirs"])
                line = f"element twoNodeLink {elem['id']} {n1} {n2} -mat {mats} -dir {dirs}"
                line += _format_link_orient(elem, ndm)
                p_delta = elem.get("pDelta")
                if p_delta:
                    p_delta_vals = p_delta
                    if ndm == 2 and len(p_delta) >= 4:
                        p_delta_vals = p_delta[2:4]
                    line += f" -pDelta {_format_list(p_delta_vals)}"
                shear_dist = elem.get("shearDist")
                if shear_dist:
                    line += f" -shearDist {_format_list(shear_dist)}"
                if elem.get("doRayleigh", False):
                    line += " -doRayleigh"
                mass = float(elem.get("mass", 0.0))
                if mass != 0.0:
                    line += f" -mass {mass}"
                f.write(line + "\n")
            elif elem["type"] == "fourNodeQuad" or elem["type"] == "bbarQuad":
                n1, n2, n3, n4 = elem["nodes"]
                t = elem["thickness"]
                mat_id = elem["material"]
                formulation = elem.get("formulation", "PlaneStress")
                f.write(
                    f"element quad {elem['id']} {n1} {n2} {n3} {n4} {t} \"{formulation}\" {mat_id}\n"
                )
            elif elem["type"] == "shell":
                n1, n2, n3, n4 = elem["nodes"]
                sec_id = elem["section"]
                f.write(f"element shell {elem['id']} {n1} {n2} {n3} {n4} {sec_id}\n")
            else:
                raise ValueError(f"unsupported element type: {elem['type']}")

        # Loads / patterns (Plain or UniformExcitation)
        loads = data.get("loads", [])
        element_loads = data.get("element_loads", [])
        pattern = data.get("pattern")
        analysis = data.get("analysis", {"type": "static_linear", "steps": 1})
        analysis_type = analysis.get("type", "static_linear")
        emit_top_level_pattern = analysis_type != "staged"
        if emit_top_level_pattern and (loads or element_loads or pattern is not None):
            if ts_list:
                if pattern is None:
                    if len(ts_list) == 1:
                        pattern = {"type": "Plain", "tag": 1, "time_series": ts_list[0]["tag"]}
                    else:
                        raise ValueError("pattern required when multiple time_series are defined")
            else:
                pattern_type = pattern.get("type", "Plain") if pattern is not None else "Plain"
                if pattern_type == "UniformExcitation":
                    raise ValueError("UniformExcitation pattern requires time_series definitions")
                if loads or element_loads:
                    _emit_time_series(
                        f, {"type": "Linear", "tag": 1, "factor": 1.0}, case_dir, data
                    )
                    ts_tags = {1}
                    if pattern is None:
                        pattern = {"type": "Plain", "tag": 1, "time_series": 1}

            if pattern is None:
                raise ValueError("pattern required when loads are present")
            pattern_type = pattern.get("type", "Plain")
            if pattern_type == "Plain":
                pattern_tag = pattern.get("tag", 1)
                ts_tag = pattern.get("time_series")
                if ts_tag is None:
                    raise ValueError("pattern missing time_series tag")
                if ts_tag not in ts_tags:
                    raise ValueError(f"pattern time_series tag {ts_tag} not found")
                f.write(f"pattern Plain {pattern_tag} {ts_tag} {{\n")
                if loads:
                    load_map = {}
                    for load in loads:
                        node_id = load["node"]
                        vec = load_map.setdefault(node_id, [0.0] * ndf)
                        dof = load["dof"]
                        if dof < 1 or dof > ndf:
                            raise ValueError(f"load dof {dof} out of range 1..{ndf}")
                        vec[dof - 1] += load["value"]
                    for node_id, vec in load_map.items():
                        f.write(f"  load {node_id} {' '.join(str(v) for v in vec)}\n")
                for elem_load in element_loads:
                    _emit_element_load(f, elem_load, ndm)
                f.write("}\n")
            elif pattern_type == "UniformExcitation":
                if loads or element_loads:
                    raise ValueError("UniformExcitation does not support nodal/element loads")
                pattern_tag = pattern.get("tag", 1)
                direction = pattern.get("direction")
                if direction is None:
                    raise ValueError("UniformExcitation pattern missing direction")
                direction = int(direction)
                if direction < 1 or direction > ndm:
                    raise ValueError("UniformExcitation direction out of range 1..ndm")
                accel_tag = pattern.get("accel", pattern.get("time_series"))
                if accel_tag is None:
                    raise ValueError("UniformExcitation pattern missing accel time_series tag")
                accel_tag = int(accel_tag)
                if accel_tag not in ts_tags:
                    raise ValueError(
                        f"UniformExcitation accel time_series tag {accel_tag} not found"
                    )
                f.write(
                    f"pattern UniformExcitation {pattern_tag} {direction} -accel {accel_tag}\n"
                )
            else:
                raise ValueError(f"unsupported pattern type: {pattern_type}")
        rayleigh = data.get("rayleigh")
        if rayleigh is not None:
            alpha_m = float(rayleigh.get("alphaM", 0.0))
            beta_k = float(rayleigh.get("betaK", 0.0))
            beta_k_init = float(rayleigh.get("betaKInit", 0.0))
            beta_k_comm = float(rayleigh.get("betaKComm", 0.0))
            f.write(f"rayleigh {alpha_m} {beta_k} {beta_k_init} {beta_k_comm}\n")

        # Analysis setup
        steps = analysis.get("steps", 1)
        constraints_handler = analysis.get("constraints", "Plain")
        dt = None
        static_nl_post_lines = None
        transient_nonlinear_emits_analyze = True

        if analysis_type == "staged":
            stages = analysis.get("stages", [])
            if not isinstance(stages, list) or len(stages) == 0:
                raise ValueError("staged analysis requires non-empty analysis.stages")
            if constraints_handler not in ("Plain", "Transformation", "Lagrange"):
                raise ValueError(f"unsupported constraints handler: {constraints_handler}")
            if mp_constraints and constraints_handler not in ("Transformation", "Lagrange"):
                raise ValueError(
                    "mp_constraints require analysis.constraints=Transformation or Lagrange"
                )

            _emit_recorders(f, recorders, node_by_id, ndf)

            for stage_idx, stage in enumerate(stages):
                if not isinstance(stage, dict):
                    raise ValueError("analysis.stages entries must be objects")
                stage_analysis = stage.get("analysis", stage)
                if not isinstance(stage_analysis, dict):
                    raise ValueError("analysis.stages[].analysis must be an object")
                stage_type = stage_analysis.get("type")
                if stage_type is None:
                    raise ValueError("analysis.stages[].analysis missing type")

                stage_ts_list = _normalize_time_series(stage.get("time_series"))
                for ts in stage_ts_list:
                    _emit_time_series(f, ts, case_dir, data)
                    ts_tags.add(ts["tag"])

                stage_pattern = stage.get("pattern", pattern if stage_idx == 0 else None)
                stage_loads = stage.get("loads", loads if stage_idx == 0 else [])
                stage_element_loads = stage.get(
                    "element_loads",
                    element_loads if stage_idx == 0 else [],
                )
                if stage_pattern is not None:
                    stage_pattern_type = stage_pattern.get("type", "Plain")
                    if stage_pattern_type in {None, "None"}:
                        if stage_loads or stage_element_loads:
                            raise ValueError(
                                "pattern type None does not support nodal/element loads"
                            )
                    elif stage_pattern_type == "Plain":
                        pattern_tag = stage_pattern.get("tag", 1)
                        ts_tag = stage_pattern.get("time_series")
                        if ts_tag is None:
                            raise ValueError("pattern missing time_series tag")
                        if ts_tag not in ts_tags:
                            raise ValueError(f"pattern time_series tag {ts_tag} not found")
                        f.write(f"pattern Plain {pattern_tag} {ts_tag} {{\n")
                        if stage_loads:
                            load_map = {}
                            for load in stage_loads:
                                node_id = load["node"]
                                vec = load_map.setdefault(node_id, [0.0] * ndf)
                                dof = load["dof"]
                                if dof < 1 or dof > ndf:
                                    raise ValueError(f"load dof {dof} out of range 1..{ndf}")
                                vec[dof - 1] += load["value"]
                            for node_id, vec in load_map.items():
                                f.write(f"  load {node_id} {' '.join(str(v) for v in vec)}\n")
                        for elem_load in stage_element_loads:
                            _emit_element_load(f, elem_load, ndm)
                        f.write("}\n")
                    elif stage_pattern_type == "UniformExcitation":
                        if stage_loads or stage_element_loads:
                            raise ValueError(
                                "UniformExcitation does not support nodal/element loads"
                            )
                        pattern_tag = stage_pattern.get("tag", 1)
                        direction = stage_pattern.get("direction")
                        if direction is None:
                            raise ValueError("UniformExcitation pattern missing direction")
                        direction = int(direction)
                        if direction < 1 or direction > ndm:
                            raise ValueError(
                                "UniformExcitation direction out of range 1..ndm"
                            )
                        accel_tag = stage_pattern.get(
                            "accel", stage_pattern.get("time_series")
                        )
                        if accel_tag is None:
                            raise ValueError(
                                "UniformExcitation pattern missing accel time_series tag"
                            )
                        accel_tag = int(accel_tag)
                        if accel_tag not in ts_tags:
                            raise ValueError(
                                f"UniformExcitation accel time_series tag {accel_tag} not found"
                            )
                        f.write(
                            f"pattern UniformExcitation {pattern_tag} {direction} -accel {accel_tag}\n"
                        )
                    else:
                        raise ValueError(
                            f"unsupported staged pattern type: {stage_pattern_type}"
                        )
                elif stage_idx > 0 and (stage_loads or stage_element_loads):
                    raise ValueError(
                        "staged analysis stage loads require an explicit stage pattern"
                    )

                stage_rayleigh = stage.get("rayleigh")
                if stage_rayleigh is not None:
                    alpha_m = float(stage_rayleigh.get("alphaM", 0.0))
                    beta_k = float(stage_rayleigh.get("betaK", 0.0))
                    beta_k_init = float(stage_rayleigh.get("betaKInit", 0.0))
                    beta_k_comm = float(stage_rayleigh.get("betaKComm", 0.0))
                    f.write(f"rayleigh {alpha_m} {beta_k} {beta_k_init} {beta_k_comm}\n")

                stage_constraints = stage_analysis.get("constraints", constraints_handler)
                if stage_constraints not in ("Plain", "Transformation", "Lagrange"):
                    raise ValueError(
                        f"unsupported constraints handler: {stage_constraints}"
                    )
                stage_numberer = _analysis_numberer(
                    stage_analysis,
                    analysis.get("numberer", "RCM"),
                )
                stage_system_line = _analysis_system_line(
                    stage_analysis,
                    analysis.get("system", "BandGeneral"),
                    analysis.get("system_options", []),
                )
                if bool(stage.get("initialize", False)):
                    f.write("initialize\n")
                f.write(f"constraints {stage_constraints}\n")
                f.write(f"numberer {stage_numberer}\n")
                f.write(stage_system_line + "\n")

                stage_steps = int(stage_analysis.get("steps", 1))
                if stage_steps < 1:
                    raise ValueError("analysis steps must be >= 1")
                stage_dt = None
                stage_static_nl_post_lines = None
                stage_transient_nl_emits_analyze = True
                if stage_type == "static_linear":
                    f.write("test NormUnbalance 1.0e-12 10\n")
                    f.write("algorithm Linear\n")
                    f.write("integrator LoadControl 1.0\n")
                    f.write("analysis Static\n")
                elif stage_type == "static_nonlinear":
                    solver_chain = _normalize_nonlinear_solver_chain(
                        stage_analysis,
                        analysis_label="static_nonlinear",
                        default_algorithm="Newton",
                        default_test_type="NormUnbalance",
                        default_tol=1.0e-10,
                        default_max_iters=20,
                        validate_test_type=_validate_static_nonlinear_test_type,
                        tcl_test_type=_tcl_static_nonlinear_test_type,
                    )
                    primary_attempt = solver_chain[0]
                    f.write(
                        _test_command_line(
                            primary_attempt["tcl_test_type"],
                            primary_attempt["tol"],
                            primary_attempt["max_iters"],
                            primary_attempt.get("test_print_flag"),
                            primary_attempt.get("test_extra_args"),
                        )
                        + "\n"
                    )
                    f.write(f"algorithm {primary_attempt['algorithm_cmd']}\n")
                    integrator = stage_analysis.get("integrator", {"type": "LoadControl"})
                    integrator_type = integrator.get("type", "LoadControl")
                    if integrator_type == "LoadControl":
                        f.write(
                            _load_control_integrator_line(
                                integrator, 1.0 / stage_steps
                            )
                            + "\n"
                        )
                        f.write("analysis Static\n")
                        if len(solver_chain) > 1:
                            stage_static_nl_post_lines = [
                                "set strut_nl_ok 0",
                                f"for {{set strut_nl_step 0}} {{$strut_nl_step < {stage_steps} && $strut_nl_ok == 0}} {{incr strut_nl_step}} {{",
                                "  set strut_nl_ok [analyze 1]",
                            ]
                            _append_solver_chain_retry_lines(
                                stage_static_nl_post_lines,
                                "strut_nl_ok",
                                "analyze 1",
                                solver_chain,
                                indent="  ",
                            )
                            stage_static_nl_post_lines.extend(
                                [
                                    "}",
                                    "if {$strut_nl_ok != 0} {",
                                    "  error \"analysis failed\"",
                                    "}",
                                ]
                            )
                    elif integrator_type == "DisplacementControl":
                        node = integrator.get("node")
                        dof = integrator.get("dof")
                        if node is None or dof is None:
                            raise ValueError("DisplacementControl requires node and dof")
                        cutback, max_cutbacks, min_du = _validate_displacement_control_cutback(
                            integrator, "DisplacementControl"
                        )
                        f.write("analysis Static\n")
                        dc_integrator_line = _displacement_control_integrator_line(
                            integrator,
                            node,
                            dof,
                            "$strut_dc_try_du",
                        )
                        targets = integrator.get("targets")
                        if targets is not None:
                            if not isinstance(targets, list) or len(targets) == 0:
                                raise ValueError(
                                    "DisplacementControl targets must be a non-empty list"
                                )
                            stage_static_nl_post_lines = (
                                _static_nonlinear_displacement_control_post_lines(
                                    node,
                                    dof,
                                    dc_integrator_line,
                                    targets,
                                    cutback,
                                    max_cutbacks,
                                    min_du,
                                    solver_chain,
                                )
                            )
                        else:
                            du = integrator.get("du")
                            if du is None or float(du) == 0.0:
                                raise ValueError(
                                    "DisplacementControl requires non-zero du when targets are omitted"
                                )
                            step_targets = [
                                float(du) * float(i + 1) for i in range(stage_steps)
                            ]
                            stage_static_nl_post_lines = (
                                _static_nonlinear_displacement_control_post_lines(
                                    node,
                                    dof,
                                    dc_integrator_line,
                                    step_targets,
                                    cutback,
                                    max_cutbacks,
                                    min_du,
                                    solver_chain,
                                )
                            )
                    else:
                        raise ValueError(
                            f"unsupported static_nonlinear integrator: {integrator_type}"
                        )
                elif stage_type == "transient_linear":
                    stage_dt = stage_analysis.get("dt")
                    if stage_dt is None or stage_dt <= 0.0:
                        raise ValueError("transient_linear requires dt > 0")
                    integrator = stage_analysis.get("integrator", {"type": "Newmark"})
                    if integrator.get("type", "Newmark") != "Newmark":
                        raise ValueError("transient_linear only supports Newmark integrator")
                    gamma = integrator.get("gamma", 0.5)
                    beta = integrator.get("beta", 0.25)
                    f.write("test NormUnbalance 1.0e-12 10\n")
                    f.write("algorithm Linear\n")
                    f.write(f"integrator Newmark {gamma} {beta}\n")
                    f.write("analysis Transient\n")
                elif stage_type == "transient_nonlinear":
                    stage_dt = stage_analysis.get("dt")
                    if stage_dt is None or stage_dt <= 0.0:
                        raise ValueError("transient_nonlinear requires dt > 0")
                    solver_chain = _normalize_nonlinear_solver_chain(
                        stage_analysis,
                        analysis_label="transient_nonlinear",
                        default_algorithm="Newton",
                        default_test_type="NormUnbalance",
                        default_tol=1.0e-10,
                        default_max_iters=20,
                        validate_test_type=_validate_transient_nonlinear_test_type,
                        tcl_test_type=lambda test_type: test_type,
                    )
                    integrator = stage_analysis.get("integrator", {"type": "Newmark"})
                    if integrator.get("type", "Newmark") != "Newmark":
                        raise ValueError(
                            "transient_nonlinear only supports Newmark integrator"
                    )
                    gamma = integrator.get("gamma", 0.5)
                    beta = integrator.get("beta", 0.25)
                    primary_attempt = solver_chain[0]
                    f.write(
                        _test_command_line(
                            primary_attempt["tcl_test_type"],
                            primary_attempt["tol"],
                            primary_attempt["max_iters"],
                            primary_attempt.get("test_print_flag"),
                            primary_attempt.get("test_extra_args"),
                        )
                        + "\n"
                    )
                    f.write(f"algorithm {primary_attempt['algorithm_cmd']}\n")
                    f.write(f"integrator Newmark {gamma} {beta}\n")
                    f.write("analysis Transient\n")
                    if len(solver_chain) > 1:
                        f.write("set strut_tr_ok 0\n")
                        f.write(
                            f"for {{set strut_tr_step 0}} {{$strut_tr_step < {stage_steps} && $strut_tr_ok == 0}} {{incr strut_tr_step}} {{\n"
                        )
                        f.write(f"  set strut_tr_ok [analyze 1 {stage_dt}]\n")
                        transient_retry_lines = []
                        _append_solver_chain_retry_lines(
                            transient_retry_lines,
                            "strut_tr_ok",
                            f"analyze 1 {stage_dt}",
                            solver_chain,
                            indent="  ",
                        )
                        for line in transient_retry_lines:
                            f.write(line + "\n")
                        f.write("}\n")
                        f.write("if {$strut_tr_ok != 0} {\n")
                        f.write("  error \"analysis failed\"\n")
                        f.write("}\n")
                        stage_transient_nl_emits_analyze = False
                elif stage_type == "modal_eigen":
                    num_modes = int(stage_analysis.get("num_modes", 0))
                    if num_modes < 1:
                        raise ValueError("modal_eigen requires num_modes >= 1")
                else:
                    raise ValueError(
                        f"unsupported staged analysis type: {stage_type}"
                    )

                if stage_type == "transient_linear" or (
                    stage_type == "transient_nonlinear"
                    and stage_transient_nl_emits_analyze
                ):
                    f.write(f"analyze {stage_steps} {stage_dt}\n")
                elif stage_type == "modal_eigen":
                    num_modes = int(stage_analysis.get("num_modes", 0))
                    f.write(f"set strut_modal_lambda [eigen {num_modes}]\n")
                elif stage_type == "static_nonlinear":
                    integrator = stage_analysis.get("integrator", {"type": "LoadControl"})
                    if stage_static_nl_post_lines is not None:
                        for line in stage_static_nl_post_lines:
                            f.write(line + "\n")
                    elif integrator.get("type", "LoadControl") == "LoadControl":
                        f.write(f"set strut_nl_ok [analyze {stage_steps}]\n")
                        f.write("if {$strut_nl_ok != 0} {\n")
                        f.write("  error \"analysis failed\"\n")
                        f.write("}\n")
                elif stage_type == "transient_nonlinear":
                    # The staged transient_nonlinear branch above either emitted a single
                    # `analyze` or a per-step fallback loop.
                    pass
                else:
                    f.write(f"analyze {stage_steps}\n")

                _emit_print_commands(f, stage)

                load_const = stage.get("load_const")
                if load_const is not None and load_const is not False:
                    if isinstance(load_const, dict):
                        lc_time = float(load_const.get("time", 0.0))
                    elif isinstance(load_const, bool):
                        lc_time = 0.0
                    else:
                        lc_time = float(load_const)
                    f.write(f"loadConst -time {lc_time}\n")
            return

        if steps < 1:
            raise ValueError("analysis steps must be >= 1")
        if constraints_handler not in ("Plain", "Transformation", "Lagrange"):
            raise ValueError(f"unsupported constraints handler: {constraints_handler}")
        if mp_constraints and constraints_handler not in ("Transformation", "Lagrange"):
            raise ValueError(
                "mp_constraints require analysis.constraints=Transformation or Lagrange"
            )
        numberer = _analysis_numberer(analysis)
        system_line = _analysis_system_line(analysis)
        if bool(data.get("initialize", False)):
            f.write("initialize\n")
        f.write(f"constraints {constraints_handler}\n")
        f.write(f"numberer {numberer}\n")
        f.write(system_line + "\n")
        if analysis_type == "static_linear":
            f.write("test NormUnbalance 1.0e-12 10\n")
            f.write("algorithm Linear\n")
            f.write("integrator LoadControl 1.0\n")
            f.write("analysis Static\n")
        elif analysis_type == "static_nonlinear":
            solver_chain = _normalize_nonlinear_solver_chain(
                analysis,
                analysis_label="static_nonlinear",
                default_algorithm="Newton",
                default_test_type="NormUnbalance",
                default_tol=1.0e-10,
                default_max_iters=20,
                validate_test_type=_validate_static_nonlinear_test_type,
                tcl_test_type=_tcl_static_nonlinear_test_type,
            )
            primary_attempt = solver_chain[0]
            f.write(
                _test_command_line(
                    primary_attempt["tcl_test_type"],
                    primary_attempt["tol"],
                    primary_attempt["max_iters"],
                    primary_attempt.get("test_print_flag"),
                    primary_attempt.get("test_extra_args"),
                )
                + "\n"
            )
            f.write(f"algorithm {primary_attempt['algorithm_cmd']}\n")
            integrator = analysis.get("integrator", {"type": "LoadControl"})
            integrator_type = integrator.get("type", "LoadControl")
            if integrator_type == "LoadControl":
                f.write(_load_control_integrator_line(integrator, 1.0 / steps) + "\n")
                f.write("analysis Static\n")
                if len(solver_chain) > 1:
                    static_nl_post_lines = [
                        "set strut_nl_ok 0",
                        f"for {{set strut_nl_step 0}} {{$strut_nl_step < {int(steps)} && $strut_nl_ok == 0}} {{incr strut_nl_step}} {{",
                        "  set strut_nl_ok [analyze 1]",
                    ]
                    _append_solver_chain_retry_lines(
                        static_nl_post_lines,
                        "strut_nl_ok",
                        "analyze 1",
                        solver_chain,
                        indent="  ",
                    )
                    static_nl_post_lines.extend(
                        [
                            "}",
                            "if {$strut_nl_ok != 0} {",
                            "  error \"analysis failed\"",
                            "}",
                        ]
                    )
            elif integrator_type == "DisplacementControl":
                node = integrator.get("node")
                dof = integrator.get("dof")
                if node is None or dof is None:
                    raise ValueError("DisplacementControl requires node and dof")
                cutback, max_cutbacks, min_du = _validate_displacement_control_cutback(
                    integrator, "DisplacementControl"
                )
                f.write("analysis Static\n")
                dc_integrator_line = _displacement_control_integrator_line(
                    integrator,
                    node,
                    dof,
                    "$strut_dc_try_du",
                )
                targets = integrator.get("targets")
                if targets is not None:
                    if not isinstance(targets, list) or len(targets) == 0:
                        raise ValueError("DisplacementControl targets must be a non-empty list")
                    static_nl_post_lines = _static_nonlinear_displacement_control_post_lines(
                        node,
                        dof,
                        dc_integrator_line,
                        targets,
                        cutback,
                        max_cutbacks,
                        min_du,
                        solver_chain,
                    )
                else:
                    du = integrator.get("du")
                    if du is None or float(du) == 0.0:
                        raise ValueError("DisplacementControl requires non-zero du when targets are omitted")
                    step_targets = [float(du) * float(i + 1) for i in range(steps)]
                    static_nl_post_lines = _static_nonlinear_displacement_control_post_lines(
                        node,
                        dof,
                        dc_integrator_line,
                        step_targets,
                        cutback,
                        max_cutbacks,
                        min_du,
                        solver_chain,
                    )
            else:
                raise ValueError(f"unsupported static_nonlinear integrator: {integrator_type}")
        elif analysis_type == "transient_linear":
            dt = analysis.get("dt")
            if dt is None or dt <= 0.0:
                raise ValueError("transient_linear requires dt > 0")
            integrator = analysis.get("integrator", {"type": "Newmark"})
            if integrator.get("type", "Newmark") != "Newmark":
                raise ValueError("transient_linear only supports Newmark integrator")
            gamma = integrator.get("gamma", 0.5)
            beta = integrator.get("beta", 0.25)
            f.write("test NormUnbalance 1.0e-12 10\n")
            f.write("algorithm Linear\n")
            f.write(f"integrator Newmark {gamma} {beta}\n")
            f.write("analysis Transient\n")
        elif analysis_type == "transient_nonlinear":
            dt = analysis.get("dt")
            if dt is None or dt <= 0.0:
                raise ValueError("transient_nonlinear requires dt > 0")
            solver_chain = _normalize_nonlinear_solver_chain(
                analysis,
                analysis_label="transient_nonlinear",
                default_algorithm="Newton",
                default_test_type="NormUnbalance",
                default_tol=1.0e-10,
                default_max_iters=20,
                validate_test_type=_validate_transient_nonlinear_test_type,
                tcl_test_type=lambda test_type: test_type,
            )
            integrator = analysis.get("integrator", {"type": "Newmark"})
            if integrator.get("type", "Newmark") != "Newmark":
                raise ValueError("transient_nonlinear only supports Newmark integrator")
            gamma = integrator.get("gamma", 0.5)
            beta = integrator.get("beta", 0.25)
            primary_attempt = solver_chain[0]
            f.write(
                _test_command_line(
                    primary_attempt["tcl_test_type"],
                    primary_attempt["tol"],
                    primary_attempt["max_iters"],
                    primary_attempt.get("test_print_flag"),
                    primary_attempt.get("test_extra_args"),
                )
                + "\n"
            )
            f.write(f"algorithm {primary_attempt['algorithm_cmd']}\n")
            f.write(f"integrator Newmark {gamma} {beta}\n")
            f.write("analysis Transient\n")
            if len(solver_chain) > 1:
                f.write("set strut_tr_ok 0\n")
                f.write(
                    f"for {{set strut_tr_step 0}} {{$strut_tr_step < {int(steps)} && $strut_tr_ok == 0}} {{incr strut_tr_step}} {{\n"
                )
                f.write(f"  set strut_tr_ok [analyze 1 {dt}]\n")
                transient_retry_lines = []
                _append_solver_chain_retry_lines(
                    transient_retry_lines,
                    "strut_tr_ok",
                    f"analyze 1 {dt}",
                    solver_chain,
                    indent="  ",
                )
                for line in transient_retry_lines:
                    f.write(line + "\n")
                f.write("}\n")
                f.write("if {$strut_tr_ok != 0} {\n")
                f.write("  error \"analysis failed\"\n")
                f.write("}\n")
                transient_nonlinear_emits_analyze = False
        elif analysis_type == "modal_eigen":
            num_modes = int(analysis.get("num_modes", 0))
            if num_modes < 1:
                raise ValueError("modal_eigen requires num_modes >= 1")
        else:
            raise ValueError(f"unsupported analysis type: {analysis_type}")

        # Recorders
        _emit_recorders(f, recorders, node_by_id, ndf)

        if analysis_type == "transient_linear" or (
            analysis_type == "transient_nonlinear" and transient_nonlinear_emits_analyze
        ):
            f.write(f"analyze {steps} {dt}\n")
        elif analysis_type == "modal_eigen":
            num_modes = int(analysis.get("num_modes", 0))
            f.write(f"set strut_modal_lambda [eigen {num_modes}]\n")
            modal_outputs = {}
            for rec in recorders:
                if rec.get("type") != "modal_eigen":
                    continue
                output = rec.get("output", "modal")
                if output not in modal_outputs:
                    modal_outputs[output] = rec
                    f.write(f"set strut_ev_file [open \"{output}_eigenvalues.out\" \"w\"]\n")
                    f.write("foreach strut_ev $strut_modal_lambda {\n")
                    f.write("  puts $strut_ev_file $strut_ev\n")
                    f.write("}\n")
                    f.write("close $strut_ev_file\n")

                modes = rec.get("modes", [])
                if not isinstance(modes, list) or len(modes) == 0:
                    raise ValueError("modal_eigen recorder requires non-empty modes")
                nodes_out = rec.get("nodes", [])
                dofs = rec.get("dofs", [])
                if not isinstance(nodes_out, list) or len(nodes_out) == 0:
                    raise ValueError("modal_eigen recorder requires non-empty nodes")
                if not isinstance(dofs, list) or len(dofs) == 0:
                    raise ValueError("modal_eigen recorder requires non-empty dofs")
                for mode in modes:
                    mode_no = int(mode)
                    if mode_no < 1 or mode_no > num_modes:
                        raise ValueError("modal_eigen recorder mode out of range")
                    for node_id in nodes_out:
                        if node_id not in node_by_id:
                            raise ValueError(f"modal_eigen recorder node {node_id} not found")
                        f.write("set strut_modal_line \"\"\n")
                        for dof in dofs:
                            if dof < 1 or dof > ndf:
                                raise ValueError(f"modal_eigen dof {dof} out of range 1..{ndf}")
                            f.write(
                                f"append strut_modal_line \"[nodeEigenvector {int(node_id)} {mode_no} {int(dof)}] \"\n"
                            )
                        f.write(
                            f"set strut_modal_file [open \"{output}_mode{mode_no}_node{int(node_id)}.out\" \"w\"]\n"
                        )
                        f.write("puts $strut_modal_file [string trim $strut_modal_line]\n")
                        f.write("close $strut_modal_file\n")
        elif analysis_type == "static_nonlinear":
            integrator = analysis.get("integrator", {"type": "LoadControl"})
            if static_nl_post_lines is not None:
                for line in static_nl_post_lines:
                    f.write(line + "\n")
            elif integrator.get("type", "LoadControl") == "LoadControl":
                f.write(f"set strut_nl_ok [analyze {steps}]\n")
                f.write("if {$strut_nl_ok != 0} {\n")
                f.write("  error \"analysis failed\"\n")
                f.write("}\n")
        else:
            f.write(f"analyze {steps}\n")

        _emit_print_commands(f, analysis)


if __name__ == "__main__":
    main()
